(function(z){
var HJ=function(a){if(z.C&&!(9<=z.Vg)){var b=!1;try{b=a.parentNode}catch(c){}return!!b}return z.nf(a.ownerDocument.body,a)};var IJ=function(a,b){var c=b.Fd();a.bc[c]=b;for(var d in z.GB)b[z.GB[d]]&&a.vk[d].push(b);b.G=a;a.Kc()&&b.enable(a)};var JJ=function(a,b,c,d){return z.Iu(a,b,c,d)};var KJ=function(a){return a.Z()&&a.ka()?new z.$t(a):null};var LJ=function(a,b,c){z.ms.call(this,b,a||z.qF.ba(),c)};
var MJ=function(a,b,c){for(var d=(b=1==b)?a.Z():a.ka(),f=b?a.xa():a.Sa(),g=a.Zb();d!=g&&d!=c&&!(b&&0!=f||!b&&f!=z.kv(d));)var h=d.parentNode,d=z.kb(h.childNodes,d),f=b?d:d+1,d=h;return JJ(b?d:a.Z(),b?f:a.xa(),b?a.ka():d,b?a.Sa():f)};
var NJ=function(a){z.Fo(a,!1);if(z.QG){var b=a;for(a=a.parentNode;a&&"HTML"!=a.tagName;){if(z.fm?"none"==a.style[z.fm].toLowerCase():(z.C||z.wg)&&"on"==a.getAttribute("unselectable")){z.Fo(a,!1,!0);for(var c=0,d=a.childNodes.length;c<d;c++){var f=a.childNodes[c];f!=b&&1==f.nodeType&&z.Fo(a.childNodes[c],!0)}}b=a;a=a.parentNode}}};var OJ=function(a){var b=a.target.tagName;"TEXTAREA"!=b&&"INPUT"!=b&&a.preventDefault()};
var PJ=function(a){var b=z.Md(a);a=new z.Ld;var c=null;a.next=function(){for(;;){if(null==c){var a=b.next();c=z.Md(a)}try{return c.next()}catch(f){if(f!==z.Nd)throw f;c=null}}};return a};var QJ=function(a,b){var c=MJ(a,1,b),c=MJ(c,0,b),d=c.Z(),f=c.ka(),g=c.xa(),c=c.Sa();if(d==f){for(;f!=b&&0==g&&c==z.kv(f);)d=f.parentNode,g=z.kb(d.childNodes,f),c=g+1,f=d;d=f}return z.Iu(d,g,f,c)};
var RJ=function(a,b){z.QG&&b.g(a,"mousedown",OJ,!0);z.Fo(a,!0);for(var c=a.getElementsByTagName("INPUT"),d=0,f=c.length;d<f;d++){var g=c[d];g.type in SJ&&NJ(g)}z.A(a.getElementsByTagName("TEXTAREA"),NJ)};var TJ=function(a,b,c){for(var d;a!=c&&(d=a.parentNode);){for(var f=d.cloneNode(!1);a.nextSibling;)f.appendChild(a.nextSibling);b&&f.insertBefore(b,f.firstChild);b=f;a=d}return b};var UJ=function(a){return!!VJ[a.tagName]};
var WJ=function(a,b){var c=z.Md(a),d=new z.Ld;d.next=function(){var a=c.next();if(b.call(void 0,a,void 0,c))return a;throw z.Nd;};return d};var XJ=function(a,b){var c=z.Md(a),d=new z.Ld,f=!0;d.next=function(){for(;;){var a=c.next();if(!f||!b.call(void 0,a,void 0,c))return f=!1,a}};return d};var YJ=function(a){return PJ(arguments)};var ZJ=function(a,b){a=z.Md(a);try{for(;;)if(b.call(void 0,a.next(),void 0,a))return!0}catch(c){if(c!==z.Nd)throw c;}return!1};var $J=function(a){this.Qe=a;this.Xy=[]};
var aK=function(a){if(!a.sy){var b=z.ev(a.Qe);a.sy=b.tagName&&"IMG"==b.tagName?b.getAttribute("alt"):z.Oo(a.Qe)}return a.sy};var bK=function(a,b,c,d){var f=new $J(a);f.Qe.href=b;c&&(a.target=c);d&&(f.Xy=d);return f};var cK=function(a,b){var c=new $J(a),d;d=(0,z.ab)(aK(c));d=dK(d)?0>d.search(/:/)?"http://"+z.rp(d):d:eK.test(d)?"mailto:"+d:null;c.Qe.href=d?d:"";b&&(a.target=b)};
var dK=function(a){if(/\s/.test(a)||eK.test(a))return!1;var b=!1;/^[^:\/?#.]+:/.test(a)||(a="http://"+a,b=!0);a=a.match(z.qe);if(-1!=z.kb(["mailto","aim"],a[1]))return!0;var c=a[3];if(!c||b&&-1==c.indexOf(".")||/[^\w\d\-\u0100-\uffff.%]/.test(c))return!1;b=a[5];return!b||0==b.indexOf("/")};var fK=function(){z.yB.call(this)};var gK=function(a){return z.zB(a).wa()};
var hK=function(a){if(z.C||z.wg){var b=a.Xe(),c=b.Zb(),d=gK(a);iK.lastIndex=0;iK.test(c.innerHTML)&&(a=KJ(b),"P"==c.tagName?jK(c,!0):(b=c.innerHTML.replace(iK,'\x3cp$1 trtempbr\x3d"temp_br"\x3e'),z.mv(c,b),c=z.vb(c.getElementsByTagName("P")),z.Od(c,function(a){"temp_br"==a.getAttribute("trtempbr")&&(a.removeAttribute("trtempbr"),z.up(z.qf(a))&&a.appendChild(z.C?d.createTextNode(" "):d.createElement("BR")),jK(a))})),a.restore())}};
var jK=function(a,b){if(z.C||z.wg){var c=a.outerHTML.replace(/<(\/?)p/gi,"\x3c$1div");b&&(c=c.replace(iK,"\x3c/div\x3e\x3cdiv$1\x3e"));z.wg&&!/<\/div>$/i.test(c)&&(c+="\x3c/div\x3e");a.outerHTML=c}};var kK=function(a){return 0==a.indexOf("+")?a.substring(1):a};var lK=function(a){a=z.pv(a);a.align&&(a.style.textAlign=a.align,a.removeAttribute("align"))};
var mK=function(a,b,c,d,f){var g=null;d&&(g=a.G.queryCommandValue("rtl")?"rtl":a.G.queryCommandValue("ltr")?"ltr":null);b=kK(b);var h,k;if(z.C){var l=b;k=[];d=null;var n=a.Xe();h=z.zB(a);if(l in nK){var q=n&&n.Zb();if(q){for(var v=z.Me("BLOCKQUOTE",null,q),F,K=0;K<v.length;K++)if(n.containsNode(v[K])){F=v[K];break}if(q=F||z.vf(q,"BLOCKQUOTE"))d=h.B("DIV",{style:"height:0"}),q.appendChild(d),k.push(d),F?n=z.Iu(F,0,d,0):n.containsNode(d)&&(n=JJ(n.Z(),n.xa(),d,0)),n.select()}}F=a.G;!F.Bc()&&!d&&l in
oK&&(F=F.m(),n&&n.isCollapsed()&&!z.jf(F)&&(d=n.Ye(0).we(),n=d.duplicate(),n.moveToElementText(F),n.collapse(!1),n.isEqual(d)&&(n=h.createTextNode(" "),F.appendChild(n),d.move("character",1),d.move("character",-1),d.select(),k.push(n))),d=h.B("DIV",{style:"height:0"}),F.appendChild(d),k.push(d));h=k[0];k=k[1]}if(z.D){h=b;var O;pK[h]&&(O=z.zB(a).B("DIV",{style:"height: 0"},"x"),a.G.m().appendChild(O));!z.E(534)&&qK[h]&&(h=a.G.m(),O=z.zB(a).B("DIV",{style:"height: 0"},"x"),h.insertBefore(O,h.firstChild));
h=O}z.B&&(O=b,z.E("1.9")&&"formatblock"==O.toLowerCase()&&(O=a.Xe(),F=O.Z(),O.isCollapsed()&&F&&"BODY"==F.tagName&&(d=O.xa(),(F=F.childNodes[d])&&"BR"==F.tagName&&(O=O.we(),O.setStart(F,0),O.setEnd(F,0)))));z.dH&&"fontsize"==b.toLowerCase()&&rK(a);O=gK(a);f&&z.UG&&(O.execCommand("styleWithCSS",!1,!0),z.wg&&sK(a));O.execCommand(b,!1,c);f&&z.UG&&O.execCommand("styleWithCSS",!1,!1);z.D&&!z.E("526")&&"formatblock"==b.toLowerCase()&&c&&/^[<]?h\d[>]?$/i.test(c)&&tK(a);/insert(un)?orderedlist/i.test(b)&&
(z.D&&!z.E(534)&&uK(a),z.C&&(vK(a),k&&z.N(k)));h&&z.N(h);g&&a.G.execCommand(g)};
var wK=function(a,b,c,d){var f=null,g=[],h=b&&b.Zb();if(h&&"IMG"==h.tagName||!b)return null;if(b.isCollapsed())b=b.Ye(0).we(),z.NG?(f=z.zB(a).createElement("A"),b.insertNode(f)):z.MG&&(b.pasteHTML("\x3ca id\x3d'newLink'\x3e\x3c/a\x3e"),f=z.zB(a).m("newLink"),f.removeAttribute("id"));else{var k=z.pp();mK(a,"CreateLink",k);z.A(a.G.m().getElementsByTagName("A"),function(a){z.wp(a.href,k)&&g.push(a)});g.length&&(f=g.pop());a=function(a){return dK(z.Oo(a))};if(g.length&&z.go(g,a)){for(a=0;b=g[a];a++)cK(b,
d);g=null}}return bK(f,c,d,g)};var rK=function(a){var b=QJ(z.aC(a.G),a.G.m());z.Od(z.dp(b,function(a,d,f){return 1==f.ec&&b.containsNode(a)}),function(a){z.tg(a,"font-size","");z.B&&0==a.style.length&&null!=a.getAttribute("style")&&a.removeAttribute("style")})};var tK=function(a){z.Od(a.Xe(),function(a){"Apple-style-span"==a.className&&(a.style.fontSize="",a.style.fontWeight="")})};
var uK=function(a){var b=!1;z.Od(a.Xe(),function(a){var d=a.tagName;if("UL"==d||"OL"==d)if(b){if(d=z.To(a)){var f=a.ownerDocument.createRange();f.setStartAfter(d);f.setEndBefore(a);if(z.vp(f.toString())&&d.nodeName==a.nodeName){for(;d.lastChild;)a.insertBefore(d.lastChild,a.firstChild);d.parentNode.removeChild(d)}}}else b=!0})};
var vK=function(a){for(a=(a=a.Xe())&&a.Ic();a&&"UL"!=a.tagName&&"OL"!=a.tagName;)a=a.parentNode;a&&(a=a.parentNode);if(a){var b=z.vb(a.getElementsByTagName("UL"));z.wb(b,z.vb(a.getElementsByTagName("OL")));z.A(b,function(a){var b=a.type;b&&!("UL"==a.tagName?xK:yK)[b]&&(a.type="")})}};var sK=function(a){var b=[],c=z.aC(a.G).Zb();do b.push(c);while(c=c.parentNode);a=YJ(z.Md(z.aC(a.G)),z.Md(b));a=z.dp(a,z.ov);z.Od(a,function(a){var b=a.style.outline;a.style.outline="0px solid red";a.style.outline=b})};
var zK=function(a){var b=null;z.Od(a,function(a,d,f){if(-1!=f.ec){a=z.pv(a).tagName;b=b||a;if(b!=a)throw b=null,z.Nd;f.gr()}});return b};var AK=function(a,b){var c=b.replace("+justify","").toLowerCase();"full"==c&&(c="justify");var d=a.G.bc.Bidi;if(d)return c==d.t0();var f=a.Xe();if(!f)return!1;for(var g=f.Zb(),d=z.lb(g.childNodes,function(a){return z.gv(a)&&f.containsNode(a,!0)}),d=d.length?d:[g],g=0;g<d.length;g++){var h=z.pv(d[g]);if(c!=BK(h))return!1}return!0};
var BK=function(a){var b=z.zg(a,"textAlign"),b=b.replace(/^-(moz|webkit)-/,"");CK[b]||(b=a.align||"left");return b};var DK=function(a,b,c,d,f){d=kK(d);if(f){var g=gK(a);g.execCommand("styleWithCSS",!1,!0)}a=b?c.queryCommandState(d):c.queryCommandValue(d);f&&g.execCommand("styleWithCSS",!1,!1);return a};
var EK=function(a,b){z.xc.call(this);this.Vu=[];for(this.Qu=[];a&&"BODY"!=a.nodeName&&a!=b;){for(var c=0,d=a.previousSibling;d;)d=d.previousSibling,++c;this.Vu.unshift(c);this.Qu.unshift(a.nodeName);a=a.parentNode}};var FK=function(a,b){for(var c,d=b,f=0;c=a.Qu[f];++f)if(d=d.childNodes[a.Vu[f]],!d||d.nodeName!=c)return null;return d};var GK=function(){z.yB.call(this)};
var HK=function(a,b){for(var c=z.aC(a.G),d=c.Ic(),f=a.G.m(),g;d&&d!=f;){var h=d.nodeName,k;(k="DIV"==h)||!(k=IK[h])||(k=!b)||(k=d,k=!(z.iv(k)&&1==k.getElementsByTagName("BR").length));if(k){if(z.wg&&g){"DIV"==h&&g==d.lastChild&&z.iv(g)&&(z.df(g,d),z.$u(g).select());break}return}z.wg&&b&&"P"==h&&"DIV"!=h&&(g=d);d=d.parentNode}if(z.C&&!z.E(9)){var l=!1,c=c.we(),d=c.duplicate();d.moveEnd("character",1);d.text.length&&(l=d.parentElement(),d=d.duplicate(),d.collapse(!1),d=d.parentElement(),l=l!=d&&d!=
c.parentElement())&&(c.move("character",-1),c.select())}a.G.rb.wa().execCommand("FormatBlock",!1,"\x3cDIV\x3e");l&&(c.move("character",1),c.select())};
var JK=function(a){if(z.NG){if((a=z.aC(a.G))&&!a.isCollapsed()){var b=!0;if(z.wg){var c=a.Z(),d=a.xa();c==a.ka()&&c.lastChild&&"BR"==c.lastChild.tagName&&d==c.childNodes.length-1&&(b=!1)}if(b){var f=a;if(f&&!f.isCollapsed()){var g=!0,b=f.Zb(),c=new EK(f.Z(),b),d=f.xa(),h;h=f;var k=h.Z();z.ov(k)&&(k=k.childNodes[h.xa()]||k);var k=z.pv(k),l=h.ka();z.ov(l)&&(l=l.childNodes[h.Sa()]||l);l=z.pv(l);h=k==l;if(k=!h)a:{var l=f,k=l.ka(),l=l.Sa(),n=k;if(z.ov(n)){var q=n.childNodes[l];if(!q||1==q.nodeType&&z.ov(q)){k=
!1;break a}}for(q=z.pv(n);q!=n;){if(z.hv(n)){k=!0;break a}n=n.parentNode}k=l!=z.kv(k)}f.Xf();(f=FK(c,b))?f=z.av(f,d):(f=z.av(b,b.childNodes.length),g=!1);f.select();h&&(h=z.pv(f.Z()),z.iv(h,!0)&&(g="\x26nbsp;",z.wg&&"LI"==h.tagName&&(g="\x3cbr\x3e"),z.mv(h,g),z.qv(h.firstChild),g=!1));k&&(f=z.pv(f.Z()),h=z.hv(f),f&&h&&(z.af(f,h.childNodes),z.N(h)));g&&(f=z.av(FK(c,b),d),f.select())}}}a=z.wv(a,!0)}else a=z.zB(a).wa(),b=a.selection.createRange(),c=z.pp(),b.pasteHTML('\x3cspan id\x3d"'+c+'"\x3e\x3c/span\x3e'),
a=a.getElementById(c),a.id="";return a};var KK=function(){};var LK=function(a){z.H.call(this);this.vw=a||window;this.$A=z.G(this.vw,"resize",this.Rz,!1,this);this.Mc=z.Qe(this.vw)};
var MK=function(a,b){z.H.call(this);this.ca=z.Ie(a);this.U=new z.xd(this);this.OD=new LK(this.ca.eb());this.Ld={};this.Ud=this.ca.B("DIV",{className:NK});z.P(this.Ud,!1);a.appendChild(this.Ud);z.tg(this.Ud,"zIndex",b);this.qo=this.Ud;this.DF=this.ca.B("DIV",{className:"tr_bubble_closebox",innerHTML:"\x26nbsp;"});this.qo.appendChild(this.DF);RJ(this.Ud,this.U);this.Qg=new z.Qn(this.Ud)};var OK=function(a,b){return z.Fb(a.Ld,function(a){return a.type==b})};
var PK=function(a,b,c,d){var f=null,g;for(g in a.Ld){var h=a.Ld[g].jD;if(!f||z.nf(h,f))f=a.Ld[g].jD}return z.Ws(f,b,a.Ud,c,null,QK,d,null,a.qR())};var RK=function(a,b,c,d,f,g){this.type=c;this.jD=f;this.ZW=g;this.element=a.B("DIV",{className:"tr_bubble_panel",id:b},a.B("DIV",{className:"tr_bubble_panel_title"},d?d+":":""),a.B("DIV",{className:"tr_bubble_panel_content"}))};var SK=function(){z.yB.call(this);this.rc=new z.xd(this);this.rP=null};var TK=function(a,b){return new MK(a,b)};
var UK=function(a){var b=a.e0||a.G.El.document.body;a.ca=z.Ie(b);var c=VK[a.G.id];c||(c=(a.rP||TK).call(null,b,a.G.kP||0),VK[a.G.id]=c);return c};var WK=function(a){if(a.aj){var b=UK(a),c=a.aj;z.N(b.Ld[c].element);delete b.Ld[c];c=z.fo(b.Ld);1>=c&&z.kj(b.Ud,"tr_multi_bubble");0==c?b.EF():b.ga();a.HH()}};var XK=function(a){return a?z.Yo("//www.zhihu.com/equation","tex",a):""};var YK=function(){SK.call(this)};var ZK=function(a){this.OQ=a};var $K=function(a){z.Lc.call(this,"change");this.isValid=a};
var aL=function(a){z.Q.call(this,a)};var bL=function(a,b,c,d,f,g,h,k){this.hb=b;this.Xn=h||[];b=k||cL.ba();k=[];c=-c;d=-d;for(var l=0;l<h.length;l++)k.push(a.L().B("DIV",{"class":b.V()+"-item",style:"width:"+f+"px;height:"+g+"px;background-position:"+c+"px "+d+"px;"})),c-=f;this.Og=a;z.jF.call(this,k,b,a.L())};var dL=function(a,b,c){z.Lc.call(this,a,c);this.LW=b};var cL=function(){};var eL=function(a,b,c){z.Q.call(this,c);this.qk=b;this.Og=a.KW};
var fL=function(a){var b=a.qm();if(b!=a.aJ){a.aJ=b;var c=!(1024<b.length);a.dispatchEvent(new $K(c));a=a.cX;var d=z.Ie(a);d.Lq(a);b&&(c?(b=XK(b),b=d.B("IMG",{src:b})):(b=z.w("Equation is too long"),b=d.B("DIV",{"class":"ee-warning"},b)),d.appendChild(a,b))}};var gL=function(a,b,c){z.Q.call(this,c);this.NF=a;this.qk=b};var hL=function(a,b,c,d){z.TE.call(this,b);this.$j=new gL(a,d,b);this.$j.render();this.$j.HC(c);this.$j.addEventListener("+equation",this.zB,!1,this)};
var iL=function(a){bL.call(this,a,"a",0,150,18,18,"\\leftarrow \\rightarrow \\leftrightarrow \\Leftarrow \\Rightarrow \\Leftrightarrow \\uparrow \\downarrow \\updownarrow \\Uparrow \\Downarrow \\Updownarrow".split(" "));z.lF(this,new z.He(12,1))};var jL=function(a){bL.call(this,a,"c",0,70,18,18,"\\leq \\geq \\prec \\succ \\preceq \\succeq \\ll \\gg \\equiv \\sim \\simeq \\asymp \\approx \\ne \\subset \\supset \\subseteq \\supseteq \\in \\ni \\notin".split(" "));z.lF(this,new z.He(7,3))};
var kL=function(a){bL.call(this,a,"g",0,30,18,18,"\\alpha \\beta \\gamma \\delta \\epsilon \\varepsilon \\zeta \\eta \\theta \\vartheta \\iota \\kappa \\lambda \\mu \\nu \\xi \\pi \\varpi \\rho \\varrho \\sigma \\varsigma \\tau \\upsilon \\phi \\varphi \\chi \\psi \\omega \\Gamma \\Delta \\Theta \\Lambda \\Xi \\Pi \\Sigma \\Upsilon \\Phi \\Psi \\Omega".split(" "));z.lF(this,new z.He(7,6))};
var lL=function(a){bL.call(this,a,"m",0,90,30,56,"x_{a};x^{b};x_{a}^{b};\\bar{x};\\tilde{x};\\frac{a}{b};\\sqrt{x};\\sqrt[n]{x};\\bigcap_{a}^{b};\\bigcup_{a}^{b};\\prod_{a}^{b};\\coprod_{a}^{b};\\left( x \\right);\\left[ x \\right];\\left\\{ x \\right\\};\\left| x \\right|;\\int_{a}^{b};\\oint_{a}^{b};\\sum_{a}^{b}{x};\\lim_{a \\rightarrow b}{x}".split(";"));z.lF(this,new z.He(10,2))};var mL=function(a){bL.call(this,a,"mn",0,0,46,18,["g","s","c","m","a"],nL.ba());z.lF(this,new z.He(5,1))};
var nL=function(){};var oL=function(a){bL.call(this,a,"s",0,50,18,18,"\\times \\div \\cdot \\pm \\mp \\ast \\star \\circ \\bullet \\oplus \\ominus \\oslash \\otimes \\odot \\dagger \\ddagger \\vee \\wedge \\cap \\cup \\aleph \\Re \\Im \\top \\bot \\infty \\partial \\forall \\exists \\neg \\angle \\triangle \\diamond".split(" "));z.lF(this,new z.He(7,5))};var pL=function(a){z.H.call(this);this.yQ=a;this.yK={};this.Yn=null;this.U=new z.xd(this);this.ty=new z.td(300);this.U.g(this.ty,"tick",this.wH)};
var qL=function(a){this.qk=a||"";z.YE.call(this,"+equation")};var rL=function(){z.yB.call(this)};var sL=function(){z.yB.call(this)};var tL=function(a,b){var c=z.aC(a.G);return z.vf(c.Zb(),"LI")||ZJ(c,function(a){return"LI"==a.tagName})?(a.G.execCommand(b.shiftKey?"+outdent":"+indent"),b.preventDefault(),!0):!1};var uL=function(a){z.yB.call(this);this.OU=a};var vL=function(a){z.H.call(this);this.XO=a};var wL=function(){z.H.call(this);this.KU=100;this.je=[];this.Zk=[];this.jv=[]};
var xL=function(a,b,c){if(b.length){var d=b.pop();c.push(d);a.jv.push({type:b==a.je?"before_undo":"before_redo",cH:b==a.je?d.zD:d.lC,state:d});1==a.jv.length&&a.qh();0!=b.length&&1!=c.length||a.dispatchEvent("state_change")}};var yL=function(a){z.yB.call(this);a=a||new wL;this.rJ&&z.nd(this.rJ);this.fg=a;this.rJ=z.G(this.fg,"state_change",this.uQ,!1,this);this.ak={};this.Io={};this.sI=null;this.nP=(0,z.t)(this.LX,this)};
var zL=function(a,b){var c=b.Ch,d,f;b.queryCommandValue("usinglorem")?(d="",f=null):(d=b.m().innerHTML,f=new AL(b),f=f.isValid()?f:null);var g=a.Io[c];if(g){if(g.rj==d)return;if(""==d||""==g.rj){var h;h=b.wv(8,"",{});if(d==h&&""==g.rj||g.rj==h&&""==d)return}g.mC=d;g.pX=f;h=a.fg;if(0==h.je.length||!g.equals(h.je[h.je.length-1])){h.je.push(g);h.je.length>h.KU&&h.je.shift();var k=h.Zk.length;h.Zk.length=0;h.dispatchEvent({type:"state_added",state:g});(1==h.je.length||k)&&h.dispatchEvent("state_change")}}a.Io[c]=
new BL(c,d,f,a.nP)};var BL=function(a,b,c,d){vL.call(this,!0);this.Po=a;this.jL=d;this.rj=b;this.yM=c};
var AL=function(a){this.ue=a;var b=a.rb.eb();a=(a=z.aC(a))&&a.Fg()&&a.eb()==b?a:null;if(z.NG){if(b=a,this.ou=!1,b){var c=z.fu(b),d=z.hu(b);if(c&&d){a=z.gu(b);var c=new EK(c,this.ue.m()),f=z.iu(b),d=new EK(d,this.ue.m());b.Ih()?(this.Ea=d,this.ZC=f,this.Ca=c,this.My=a):(this.Ea=c,this.ZC=a,this.Ca=d,this.My=f);this.ou=!0}}}else z.MG&&(b=a,this.ou=!1,b&&(a=b.Ye(0).we(),z.nf(this.ue.m(),a.parentElement())&&(b=this.ue.rb.wa().body.createTextRange(),b.moveToElementText(this.ue.m()),d=a.duplicate(),d.collapse(!0),
d.setEndPoint("StartToStart",b),this.Ea=CL(d),a=a.duplicate(),a.setEndPoint("StartToStart",b),this.Ca=CL(a),this.ou=!0)))};var CL=function(a){var b=a.duplicate(),c=a.text,d=c.length;b.collapse(!0);b.moveEnd("character",d);for(var f,g=10;(f=b.compareEndPoints("EndToEnd",a))&&(d-=f,b.moveEnd("character",-f),--g,0!=g););a=0;for(b=c.indexOf("\n\r");-1!=b;)++a,b=c.indexOf("\n\r",b+1);return d+a};
var DL=function(a,b){z.H.call(this);this.ea=new z.xd(this);this.ue=a;this.Nb=b;this.fC=[];z.dh(this.Nb,function(a){a.tb&&this.fC.push(EL(a.xe()))},this);this.Nb.lf(!1);this.ea.g(this.ue,"cvc",this.GZ).g(this.Nb,"action",this.uR)};var EL=function(a){return a};var FL=function(a,b){z.mA.call(this,a||z.pF.ba(),b)};var GL=function(a){z.yB.call(this);this.ll=z.um.Ln+"/upload";z.Mb(this.J={},this.defaults,a||{})};
var HL=function(a){var b=z.zB(a),c=(0,window.$)('\x3cdiv class\x3d"editable-dropzone"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"cell"\x3e\x3cdiv\x3e拖拽至此处上传\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e');b.yA(c[0],a.G.m());return c};
var IL=function(a){var b=z.zB(a),c=b.B("IMG",{"class":"",style:"display:block",src:z.um.aD+"/img/spinner2.gif"}),d=z.aC(a.G);d&&z.Av(d)&&z.nf(a.G.m(),d.Zb())?d.fj(c):z.iv(a.G.Ka)?z.ef(a.G.m(),c,0):a.G.m().appendChild(c);z.C||(z.rv(c,!1),b.eb().focus());z.cC(a.G);return(0,window.$)(c)};
var JL=function(a,b){var c=[{display:"none"},{display:"table",width:a.YD.width(),height:a.YD.height(),"background-color":"rgba(255, 255, 255, 0.5)"}];c[2]=window.$.extend({},c[1],{"background-color":"rgba(245, 245, 245, 0.5)"});a.mN.css(c[b])};
var KL=function(a,b){var c=new window.FormData;c.append("via","xhr2");c.append("upload_file",b);var d;d=window.$.ajaxSettings.xhr();d.withCredentials=!0;var f=window.$.ajax({url:a.ll,data:c,processData:!1,contentType:!1,xhr:function(){return d},type:"POST"}).done(function(a){"string"===window.$.type(a)&&(a=JSON.parse(a));if(1===a.code)z.W.message(a.msg);else{var b=new window.Image;b.src=a.msg[0];b.setAttribute("originImgSrc",b.src.replace("_m.jpg","_r.jpg"));b.setAttribute("data-rawWidth",a.msg[1]);
b.setAttribute("data-rawHeight",a.msg[2]);f.hE.after(b)}}).fail(function(){z.W.message("上传失败！\x3e_\x3c")}).always(function(){f.hE.remove()});f.hE=IL(a)};var LL=function(){z.yB.call(this)};var ML=function(a){return a&&"BR"===a.tagName};
var NL=function(a,b){function c(a,b){return{NC:a,OJ:b}}z.D&&(a.normalize(),b=z.Xu());var d=OL(b);if(!d)return c(!1,null);if(z.iv(a))return c(!0,a);for(var f=d;f!==a;){if(z.hv(f))return c(!1,null);f=f.parentNode}if(ML(d)&&ML(d.previousSibling))return c(!0,d);d=b.Zb();return!d||1!==d.nodeType||d.childNodes.length&&!z.iv(d)?c(!1,null):c(!0,d)};var OL=function(a){var b=a.ka(),c=a.Sa();a=a.Ic();var d=a.childNodes.length;3!==b.nodeType&&d&&(b=a.childNodes[c===d?d-1:c]);return b};
var PL=function(a){z.Q.call(this);z.Mb(this.J={},this.defaults,a||{});this.Ie=null};var QL=function(a){var b=z.ha(a);a=b.next().value;b=b.next().value;return{label:a,value:b,toString:z.hb(a)}};var RL=function(a){var b=z.pb(SL,function(b){var d=z.ha(b);b=d.next().value;d=d.next().value;return b===a||d===a});return b&&QL(b)};
var TL=function(a,b,c){var d=a.J,f={},g=new z.ws(UL,!1),h=new z.$s(c,f);c=new z.Ns(null,null,!1);g.gj=function(a){return function(b,c,d){(0,z.ab)(b)?a.apply(this,arguments):d(b,UL)}}(g.gj);f.rd=function(b,c,f){b=b.data;b.value===a.Ie&&(z.V.add(f,d.zF),f.appendChild(z.M("i","icon "+d.zF)));f.appendChild(window.document.createTextNode(b.toString()))};f=new z.zs(g,h,c);c.Y=f;c.Fl(b);return f};
var VL=function(a,b,c){var d=a.J,f=a.o(),g=TL(a,b,c);g.Gk=20;f.g(g,"suggestionsupdate",function(){g.Cg(g.kd+0)}).g(g,"update",function(a){this.GB(a.hj)}).g(g,"dismiss",function(){this.lj(!0)});b=g.M;b.className=d.sU;b.Yh=d.AW;b.ax=d.jh;a.Y=g};var WL=function(a){z.yB.call(this);z.Mb(this.J={},this.defaults,a||{});this.Uy=this.Nb=null};var XL=function(a){return"P"===a.tagName};var YL=function(a){return 3===a.nodeType};var ZL=function(a){return a&&"PRE"===a.tagName};
var $L=function(a){var b,c=new z.hy(ZL,!1,null,a),d=z.M("div",{style:"display:none"});z.Tx(c,new z.rg(4,0,0,0));z.fy(c,new z.rg(4,0,0,0));c.er=150;c.pp=100;c.ai(d);c.className="hc-lang-select";z.G(c,"beforeshow",function(a){b=a.target.anchor;c.setPosition(new z.Qx(b,1));if(b.lang){a=f;var d=RL(b.lang);d&&a.Da(d.value);f.lj(!0)}else f.bl("选择语言")});z.G(c,"beforehide",function(c){b=null;f.Da(null);if((c=c.target)&&a.contains(c)&&ZL(c))return!1});var f=new PL;f.render(d);z.G(f,"change",function(a){b&&
(b.lang=a.zW.value,c.F(!1))});return{tz:z.hb(c),r0:z.hb(f),dispose:function(){c.dispose();f.dispose()}}};
var aM=function(a){function b(a){return z.rb(f,a)}function c(){var a=window.document.createTextNode("\n");f.push(a);return a}var d=window.document.createElement("div");d.innerHTML=a;var f=[],g=z.kp(b);a=z.Po(d,UJ);z.A(a,function(a){a.lastChild&&"BR"===a.lastChild.tagName&&a.removeChild(a.lastChild);a.firstChild||a.appendChild(window.document.createTextNode(""));a.insertBefore(c(),a.firstChild);a.appendChild(c())});a=z.vb(d.getElementsByTagName("br"));z.A(a,function(a){a!==a.parentNode.lastChild&&
z.Vo(window.document.createTextNode("\n"),a)});d=z.Po(d,YL);d=z.np(function(a){return z.lb(a,function(c,d){var f=a[d-1];return!f||!(b(f)&&b(c))})},function(a){var b=z.ip(a,g);return-1!==b?a.slice(0,b+1):a},function(a){var b=z.qb(a,g);return-1!==b?a.slice(b):a})(d);return z.mb(d,function(a){return a.nodeValue}).join("").replace(/\xa0/g," ")};var bM=function(a,b){a.Nb&&a.Uy&&z.dh(a.Nb,function(a){a instanceof z.sF&&a.gb(!b||z.rb(this.Uy,a.xe()))},a)};
var cM=function(a,b,c){for(a=a.G.Ka;b!==a;){if(c(b))return b;b=b.parentNode}};var dM=function(a){var b,c=z.Xu();c&&a.G.Ka.contains(c.Zb())?(b=c.Z(),a=(b=cM(a,b,ZL))?"1":"2"):a="0";return{state:a,vv:c,code:b}};var eM=function(a,b){var c=window.document.createTextNode(b);a.fj(c);z.rv(c)};var fM=function(a,b,c){a.Bo("i",function(a,f){b.fj(a);a=f();c=z.Ka(c);z.Vo(window.document.createTextNode(c),a)})};
var gM=function(a,b){for(var c=a,d=[];c&&c!==b;)d.push([c.parentNode.childNodes.length,z.kb(c.parentNode.childNodes,c)]),c=c.parentNode;return d};var hM=function(a){var b=dM(a);a=b.vv;var c=b.code;if("1"===b.state){var b=function(a,b){return b===a.length||iM&&b===a.length-1&&"\n"===a.slice(-1)},d=a.ka(),f=gM(d,c),f=!f.length||z.go(f,function(a){return a[0]===a[1]+1}),g=YL(d);f&&(!g||g&&b(d.nodeValue,a.Sa()))&&jM(c)}};var jM=function(a){z.hv(a)||z.df(window.document.createElement("br"),a)};
var kM=function(a,b){a.Bo("i",function(a,d){b.fj(a);(0,window.setTimeout)(function(){var b=window.document.createTextNode("\r");a=d();z.Vo(b,a);z.rv(b)})})};var lM=function(a,b,c){var d=a.J,f;b.Xf();var g=mM(a,b);g?(f=window.document.createElement("PRE"),g.parentNode.insertBefore(f,g)):a.Bo("PRE",function(a,c){b.insertNode(a);f=c()});!c&&z.C&&(c=" ");f.lang=d.gQ;z.of(f,c);z.iv(f)?z.qv(f.firstChild):z.rv(f.lastChild);jM(f)};
var mM=function(a,b){function c(a){return a.parentNode.insertBefore(window.document.createTextNode(""),a)}var d=z.wv(b,!0),f=d.node,g,h=a.G.Ka,k=cM(a,f,z.lp(UJ,z.kp(XL)))||h;if(YL(f)){var l=f.parentNode;!f.nodeValue&&l!==h&&z.iv(l)?(g=c(l),f=c(g),l.parentNode.removeChild(l)):g=z.C&&d.offset===f.length?z.df(window.document.createTextNode(""),f):f.splitText(d.offset)}else"BR"===f.tagName&&(g=f,f=c(f));return g?(d=TJ(f,g,k),f=d.firstChild,z.af(k,d.childNodes),f):null};
var nM=function(){z.yB.call(this);this.xW=null};var oM=function(a){a.push("\x3cbr\x3e")};var pM=function(a){if(!z.aC(a.G).isCollapsed()){var b=a.xW||(0,z.t)(a.$K,a);qM(a,b);z.zB(a).wa().execCommand("RemoveFormat",!1,void 0);z.YG&&qM(a,function(a){var b=z.E("528")?/&nbsp;/g:/\u00A0/g;return a.replace(b," ")})}};var rM=function(a,b){for(var c=a.G.m();b&&b!=c;){if("TABLE"==b.tagName)return b;b=b.parentNode}return null};
var qM=function(a,b){var c=z.aC(a.G);if(!(1<c.ik())){if(z.B||z.Gc){var d=QJ(c,a.G.m()),f=rM(a,d.Z()),g=rM(a,d.ka());if(f||g){if(f==g)return;var h,k=c;h=f;var c=g,d=new z.Cv(k),l=k.Z(),n=k.xa(),q=k.ka(),k=k.Sa(),v=z.zB(a);if(h){var F=v.createTextNode("");z.df(F,h);l=F;n=0}c&&(F=v.createTextNode(""),z.cf(F,c),q=F,k=0);z.Iu(l,n,q,k).select();h=d;f||(c=z.N(z.au(h,!0)),a.YC=c);g||(c=z.N(z.au(h,!1)),a.Ly=c);c=z.aC(a.G);d=QJ(c,a.G.m())}d.select();c=d}l=c;c=z.zB(a).B("DIV");d=l.we();z.NG?c.appendChild(d.cloneContents()):
z.MG&&(n=l.ae(),n=n.replace(/\r\n/g,"\r"),q=n.length,l=q-z.rp(n).length,n=q-z.qp(n).length,d.moveStart("character",l),d.moveEnd("character",-n),l=d.htmlText,"Formatted"==d.queryCommandValue("formatBlock")&&(l=z.La(d.htmlText)),c.innerHTML=l);l=b(c.innerHTML);v=z.aC(a.G);c=z.zB(a);n=z.pp();d=z.pp();l='\x3cspan id\x3d"'+n+'"\x3e\x3c/span\x3e'+l+'\x3cspan id\x3d"'+d+'"\x3e\x3c/span\x3e';k=z.pp();q='\x3cspan id\x3d"'+k+'"\x3e\x3c/span\x3e';if(z.MG){F=v.Ye(0).we();F.pasteHTML(q);for(var K;(K=F.parentElement())&&
z.iv(K)&&!z.lv(K);){v=K.nodeName;if("TD"==v||"TR"==v||"TH"==v)break;z.N(K)}F.pasteHTML(l);(k=c.m(k))&&z.N(k)}else if(z.NG){c.wa().execCommand("insertImage",!1,k);v=new RegExp("\x3c[^\x3c]*"+k+"[^\x3e]*\x3e");K=z.aC(a.G).Zb();3==K.nodeType&&(K=K.parentNode);for(;!v.test(K.innerHTML);)K=K.parentNode;if(z.B)z.mv(K,K.innerHTML.replace(v,l));else{z.mv(K,K.innerHTML.replace(v,q));for(K=k=c.m(k);(K=k.parentNode)&&z.iv(K)&&!z.lv(K);){v=K.nodeName;if("TD"==v||"TR"==v||"TH"==v)break;z.df(k,K);z.N(K)}z.mv(K,
K.innerHTML.replace(new RegExp(q,"i"),l))}}K=c.m(n);c=c.m(d);z.Iu(K,0,c,c.childNodes.length).select();z.N(K);z.N(c);(z.B||z.Gc)&&h&&(c=z.aC(a.G),K=a.G.m(),a.YC&&(K.insertBefore(a.YC,K.firstChild),a.YC=null),a.Ly&&(K.appendChild(a.Ly),a.Ly=null),K=null,d=z.au(h,!0),l=z.au(h,!1),d&&l&&(K=z.Iu(d,0,l,0)),f=f?K:c,g=g?K:c,JJ(f.Z(),f.xa(),g.ka(),g.Sa()).select(),h.dispose())}};var sM=function(){nM.call(this)};var tM=function(a){z.TE.call(this,a);this.U=new z.xd(this)};
var uM=function(a,b,c,d,f){z.Lc.call(this,"ok");this.QZ=a;this.PZ=b;this.QM=f;this.IY=c;this.poster=d};var vM=function(a,b){b=z.Gr(b);if(!b)return!1;var c=b.match(/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]{2,256}\.[a-z]{2,4}\b(\/[\-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)?/gi);c||(z.P(a.Nh,!1),a.Cf.innerHTML="我们无法识别你输入的视频页地址",z.P(a.Cf,!0));return c};var wM=function(){z.YE.call(this,xM);this.U=new z.xd(this)};var yM=function(){};
var zM=function(a,b){var c=[];b.enableFullScreen&&c.push("toggleFullScreen");c.push("+bold","+italic","+underline",new FL,"+blockquote","+code","+insertOrderedList","+insertUnorderedList","+equation");b.canUploadMedia_&&c.push(new FL,"image",xM);b.useRemoveFormat_&&c.push(new FL,"+removeFormat");for(var d=z.Ie(a),f=[],g=0,h;h=c[g];g++){if(z.oa(h)){var k=void 0;if(h=z.tI[h]){var k=h.factory||z.YF,l=h.Ba,n=h.na,q=h.caption,v=h.Wa,F=d||z.Ie(),k=k(l,n,q,v,null,F);h.tb&&(k.tb=!0)}h=k}h&&f.push(h)}c=z.Ie(a);
c=new LJ(z.qF.ba(),z.EG,c);d=z.Og(a);c.ci(d);c.lf(!1);for(g=0;h=f[g];g++)h.dc(32,!1),h.ci(d),c.K(h,!0);c.render(a);return c};var AM=function(a,b){var c=a.m(),d=new z.xC;d.w(c);var f=z.M("div",{style:"display:none",className:"tr-spinner spinner-gray"});b.m().appendChild(f);d.on("willScrape",function(){z.P(f,!0)}).on("didScrape",function(){z.P(f,!1)});z.Ac(a,d)};z.Ux.prototype.uz=z.Z(40,function(){return this.m().innerHTML});
z.uu.prototype.Fg=z.Z(38,function(){var a=this.at.body.createTextRange();a.moveToElementText(this.at.body);return this.lh(new z.uu(a,this.at),!0)});z.Gu.prototype.Fg=z.Z(37,function(){return(!this.Aa||HJ(this.Aa))&&(!this.va||HJ(this.va))&&(!(z.C&&!(9<=z.Vg))||z.Ku(this).Fg())});z.Mu.prototype.Fg=z.Z(36,function(){var a=!1;try{a=z.go(this.Mi(),function(a){return z.C?!!a.parentNode:z.nf(a.ownerDocument.body,a)})}catch(b){}return a});z.Su.prototype.Fg=z.Z(35,function(){return z.go(z.eu(this),function(a){return a.Fg()})});
z.bu.prototype.gr=z.Z(34,function(){var a=this.Xc?-1:1;this.ec==a&&(this.ec=-1*a,this.depth+=this.ec*(this.Xc?-1:1))});z.lu.prototype.gr=z.Z(33,function(){z.lu.v.gr.apply(this);if(z.nf(this.node,this.va))throw z.Nd;});z.bq.prototype.lj=z.Z(29,function(a,b){var c=a.Jd(),d=this.V()+"-collapse-left",f=this.V()+"-collapse-right";a.Zj(c?f:d,!!(b&1));a.Zj(c?d:f,!!(b&2))});z.lq.prototype.lj=z.Z(28,function(a){this.M.lj(this,a)});z.Cj.prototype.wt=z.Z(24,function(){z.Ej(this);return this.Cc});
z.TE.prototype.wt=z.Z(23,function(a){return this.Af.Dc.If(a)});z.$c.prototype.sm=z.Z(2,function(a,b){var c=this.vc[a.toString()],d=[];if(c)for(var f=0;f<c.length;++f){var g=c[f];g.Ql==b&&d.push(g)}return d});z.H.prototype.sm=z.Z(1,function(a,b){return this.te.sm(String(a),b)});z.y(LJ,z.ms);LJ.prototype.ye=function(a){LJ.v.ye.call(this,a);this.Sf||z.qs(this)};
var SJ={text:!0,file:!0,url:!0},VJ={ADDRESS:!0,ARTICLE:!0,ASIDE:!0,BLOCKQUOTE:!0,BODY:!0,CAPTION:!0,CENTER:!0,COL:!0,COLGROUP:!0,DETAILS:!0,DIR:!0,DIV:!0,DL:!0,DD:!0,DT:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,ISINDEX:!0,OL:!0,LI:!0,MAP:!0,MENU:!0,NAV:!0,OPTGROUP:!0,OPTION:!0,P:!0,PRE:!0,SECTION:!0,SUMMARY:!0,TABLE:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0,UL:!0},xM,BM,eK=/^[\w-]+(\.[\w-]+)*\@([\w-]+\.)+(\d+|\w\w+)$/i;z.y(fK,z.yB);fK.prototype.Fd=function(){return"BTF"};var CM={B_:"+link",j_:"+createLink",r_:"+formatBlock",v_:"+indent",I_:"+outdent",O_:"+strikeThrough",t_:"+insertHorizontalRule",P_:"+subscript",Q_:"+superscript",T_:"+underline",f_:"+bold",w_:"+italic",q_:"+fontSize",p_:"+fontName",o_:"+foreColor",$Z:"+backColor",H_:"+insertOrderedList",X_:"+insertUnorderedList",x_:"+justifyCenter",y_:"+justifyFull",A_:"+justifyRight",z_:"+justifyLeft"},DM=z.fp(CM);fK.prototype.ef=function(a){return a in DM};
var EM=["+createLink"];z.e=fK.prototype;z.e.QI=function(a){return z.rb(EM,a)};z.e.Xe=function(){return z.aC(this.G)};
z.e.Df=function(a,b,c,d){var f,g,h,k,l,n=b;switch(a){case "+backColor":if(null!==n)if(z.VG){a=n;g=z.aC(this.G);var q,v;g&&g.isCollapsed()&&(q=z.zB(this).createTextNode(z.B?" ":""),h=g.Z(),v=1==h.nodeType?h:h.parentNode,""==v.innerHTML?(v.style.textIndent="-10000px",v.appendChild(q)):(v=z.zB(this).B("SPAN",{style:"text-indent:-10000px"},q),g.fj(v)),z.$u(q).select());mK(this,"hiliteColor",a,!1,!0);q&&(z.B&&(q.data=""),v.style.textIndent="")}else z.wg?mK(this,"hiliteColor",n):mK(this,a,n);break;case "+createLink":l=
wK(this,b,c,d);break;case "+link":a:{l=n;this.G.Qf||z.zB(this).eb().focus();g=(a=this.Xe())&&a.Zb();if((g=z.vf(g,"A"))&&z.wf(g,z.lv))z.ff(g);else if(l=wK(this,a,"/",l)){if(!this.G.execCommand("link",l))if(h=this.G.El.prompt(z.EH,"http://"))a=aK(l)||h,g=l.Qe,g.href=h,n=aK(l),a!=n&&(h=z.ev(g),h.tagName&&"IMG"==h.tagName?h.setAttribute("alt",a?a:""):(3==h.nodeType&&(h=h.parentNode),z.Oo(h)!=n&&(h=g),z.bf(h),g=z.Ie(h),h.appendChild(g.createTextNode(a))),l.sy=null),a=l.Qe,z.ZG?(g=a.nextSibling,g&&3==g.nodeType&&
(z.Ia(g.data," ")||z.Ia(g.data," "))||(g=z.Ie(a).createTextNode(" "),z.df(g,a)),z.av(g,1).select()):z.rv(a,!1);else{a=z.$u(l.Qe);a=new z.Cv(a);z.ff(l.Qe);for(l.Qe=null;l.Xy.length;)z.ff(l.Xy.pop());a.restore().select();l=null;break a}break a}l=null}break;case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":mK(this,a,null,!1,!0);z.B&&mK(this,a,null,!1,!0);z.UG&&z.B||z.Od(z.aC(this.G),lK);break;default:z.C&&"+formatBlock"==a&&n&&(n="\x3c"+n+"\x3e");if("+foreColor"==a&&
null===n)break;switch(a){case "+indent":case "+outdent":z.UG&&(z.B&&(g=!0),z.wg&&(g="+outdent"==a?!gK(this).queryCommandEnabled("outdent"):!0));case "+insertOrderedList":case "+insertUnorderedList":if(q=z.bH)q=gK(this),q=DK(this,!0,q,a,void 0);q?h="P"!=this.G.queryCommandValue("+defaultTag"):z.cH||hK(this);z.B&&z.aH&&!this.queryCommandValue(a)&&(q=this.G.queryCommandValue("+defaultTag"),"P"==q||"DIV"==q?q=!1:(q=this.Xe(),q.isCollapsed()&&3!=q.Ic().nodeType?(f=z.zB(this).createTextNode(" "),q.insertNode(f,
!1),z.$u(f).select(),q=!0):q=!1),k|=q);case "+formatBlock":f=!!this.G.bc.Bidi;break;case "+subscript":case "+superscript":z.$G&&!this.queryCommandValue(a)&&(q="+subscript"==a?"+superscript":"+subscript",v=kK(q),this.queryCommandValue(q)||gK(this).execCommand(v,!1,null),gK(this).execCommand(v,!1,null));break;case "+underline":case "+bold":case "+italic":g=z.B&&z.UG&&this.queryCommandValue(a);break;case "+foreColor":case "+fontName":g=z.UG&&z.B}mK(this,a,n,f,!!g);k&&gK(this).execCommand("Delete",!1,
!0);h&&gK(this).execCommand("FormatBlock",!1,"\x3cdiv\x3e")}z.B&&!this.G.Eh&&z.zB(this).eb().focus();return l};
z.e.queryCommandValue=function(a){var b;switch(a){case "+link":return a=(a=this.Xe())&&a.Zb(),a=z.vf(a,"A"),!!a&&!!z.wf(a,z.lv);case "+justifyCenter":case "+justifyFull":case "+justifyRight":case "+justifyLeft":return AK(this,a);case "+formatBlock":return zK(z.aC(this.G));case "+indent":case "+outdent":case "+insertHorizontalRule":return!1;case "+fontSize":case "+fontName":case "+foreColor":case "+backColor":return this.rv(gK(this),a,z.UG&&z.B);case "+underline":case "+bold":case "+italic":b=z.UG&&
z.B;default:var c=gK(this);return DK(this,!0,c,a,b)}};z.e.EK=function(a){z.SG&&a.match(/^\s*<script/i)&&(a="\x26nbsp;"+a);z.TG&&(a=a.replace(/<(\/?)strong([^\w])/gi,"\x3c$1b$2"),a=a.replace(/<(\/?)em([^\w])/gi,"\x3c$1i$2"));return a};z.e.DP=function(a){a=a.getElementsByTagName("IMG");for(var b=0,c;c=a[b];b++)if(z.C){c.removeAttribute("tabIndex");c.removeAttribute("tabIndexSet");var d=c;null!==d&&"removeAttribute"in d&&d.removeAttribute(z.va);try{delete d[z.va]}catch(f){}c.bV&&(c.tabIndex=c.bV)}};
z.e.EP=function(a){if(z.D){for(var b=z.Ne(this.G.rb.Ra,"HEAD",void 0,void 0),c=[],d=b.length,f=1;f<d;++f)for(var g=b[f].getElementsByTagName("STYLE"),h=g.length,k=0;k<h;++k)c.push(g[k].outerHTML);return c.join("")+a}return a};z.e.Mt=function(a,b,c){if(!c)return!1;var d;switch(b){case "b":d="+bold";break;case "i":d="+italic";break;case "u":d="+underline";break;case "s":return!0}return d?(this.G.execCommand(d),!0):!1};
var iK=z.C?/<br([^\/>]*)\/?>/gi:/<br([^\/>]*)\/?>(?!<\/(div|p)>)/gi,oK={indent:1,outdent:1,insertOrderedList:1,insertUnorderedList:1,justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,ltr:1,rtl:1},nK={insertOrderedList:1,insertUnorderedList:1},yK={1:1,a:1,A:1,i:1,I:1},xK={disc:1,circle:1,square:1},pK={justifyCenter:1,justifyFull:1,justifyRight:1,justifyLeft:1,formatBlock:1},qK={insertOrderedList:1,insertUnorderedList:1},CK={center:1,justify:1,right:1,left:1};
fK.prototype.rv=function(a,b,c){return DK(this,!1,a,b,c)};z.y(EK,z.xc);EK.prototype.toString=function(){for(var a=[],b,c=0;b=this.Qu[c];c++)a.push(this.Vu[c]+","+b);return a.join("\n")};EK.prototype.D=function(){delete this.Vu;delete this.Qu};z.y(GK,z.yB);z.e=GK.prototype;z.e.tag="DIV";z.e.Fd=function(){return"EnterHandler"};z.e.enable=function(a){GK.v.enable.call(this,a);!z.eH||"P"!=this.tag&&"DIV"!=this.tag||z.zB(this).wa().execCommand("opera-defaultBlock",!1,this.tag)};z.e.EK=function(a){return!a||z.up(a)?z.SG?this.nR():"":a};z.e.nR=z.hb("\x3cbr\x3e");
z.e.nS=function(a){if(z.B&&this.G.Eh)return!1;if(8==a.keyCode){var b=z.aC(this.G),c=this.G.m(),b=b&&b.Z();c.firstChild==b&&z.iv(b)&&(a.preventDefault(),a.stopPropagation())}else if(13==a.keyCode)if(z.B){if(!a.shiftKey){var c=z.aC(this.G),b=!c||c.isCollapsed(),d=JK(this),f=this.G.execCommand("+splitBlockquote",d);f&&(a.preventDefault(),a.stopPropagation());z.NG||d.removeNode(!0);f||this.aS(a,b,c)}}else{this.G.Ii();c=JK(this);if(b=!!this.G.execCommand("+splitBlockquote",c))a.preventDefault(),a.stopPropagation();
z.NG||c.removeNode(!0);z.D&&this.bS(a);if(z.C||z.wg)HK(this);else if(!b&&z.D){if(b=c=z.aC(this.G))a:{for(b=c.Zb();b;b=b.parentNode)if(UJ(b)){b="BLOCKQUOTE"==b.tagName;break a}b=!1}if(b){b=z.zB(this);d=b.createElement("BR");c.insertNode(d,!0);if(c=UJ(d.parentNode)){for(c=d.nextSibling;c&&3==c.nodeType&&!c.nodeValue;)c=c.nextSibling;c=!c}c&&z.cf(b.createElement("BR"),d);z.rv(d,!1);a.preventDefault()}}this.G.Bf()}else z.B&&46==a.keyCode&&(b=z.aC(this.G),b.isCollapsed()&&(c=b.ka(),1==c.nodeType&&(b=c.childNodes[b.Sa()])&&
"BR"==b.tagName&&(d=z.fv(z.dp(new z.cv(b,!1,!0),z.gv)),f=b.nextSibling,c.removeChild(b),a.preventDefault(),f&&UJ(f)&&(d&&"BR"!=d.tagName&&!UJ(d)?z.av(d,z.kv(d)).select():(a=z.ev(f),z.av(a,0).select())))));return!1};z.e.Lt=function(a){if(z.B&&this.G.Eh)return!1;(z.C||z.wg)&&13==a.keyCode&&HK(this,!0);return!1};z.e.bS=z.r;z.e.aS=z.r;var IK={LI:!0,DIV:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0};var FM=new KK,GM=["click",z.B?"keypress":"keydown","keyup"];KK.prototype.g=function(a,b,c,d,f){function g(a){var c=z.cd(b),f=z.lf(a.target)?a.target.getAttribute("role")||null:null;"click"==a.type&&z.Tc(a)?c.call(d,a):13!=a.keyCode&&3!=a.keyCode||"keyup"==a.type?32!=a.keyCode||"keyup"!=a.type||"button"!=f&&"tab"!=f||(c.call(d,a),a.preventDefault()):(a.type="keypress",c.call(d,a))}g.Ek=b;g.Hv=d;f?f.g(a,GM,g,c):z.G(a,GM,g,c)};
KK.prototype.pa=function(a,b,c,d,f){for(var g,h=0;g=GM[h];h++){var k;var l=a;k=g;var n=!!c;k=z.Vc(l)?l.sm(k,n):l?(l=z.ed(l))?l.sm(k,n):[]:[];for(l=0;n=k[l];l++)if(n.listener.Ek==b&&n.listener.Hv==d){f?f.pa(a,g,n.listener,c,d):z.md(a,g,n.listener,c,d);break}}};z.y(LK,z.H);LK.prototype.yh=function(){return this.Mc?this.Mc.clone():null};LK.prototype.D=function(){LK.v.D.call(this);this.$A&&(z.nd(this.$A),this.$A=null);this.Mc=this.vw=null};LK.prototype.Rz=function(){var a=z.Qe(this.vw);z.Xo(a,this.Mc)||(this.Mc=a,this.dispatchEvent("resize"))};z.y(MK,z.H);var NK="tr_bubble";z.e=MK.prototype;z.e.D=function(){MK.v.D.call(this);z.N(this.Ud);this.Ud=null;this.U.dispose();this.U=null;this.OD.dispose();this.OD=null};z.e.S=function(){return this.qo};z.e.Zb=function(){return this.Ud};z.e.$S=function(){this.W()&&this.ga()};z.e.nn=function(a){this.Qg.nn(a)};z.e.EF=function(){this.Qg.F(!1)};z.e.FS=function(){for(var a in this.Ld)z.N(this.Ld[a].element);this.Ld={};z.kj(this.Ud,"tr_multi_bubble");this.U.removeAll();this.dispatchEvent("hide")};
z.e.W=function(){return this.Qg.W()};var HM=z.C?4:2,QK=new z.rg(HM,0,HM,0);MK.prototype.ga=function(){var a=null,b=!0,c;for(c in this.Ld)var d=this.Ld[c],a=d.jD,b=b&&d.ZW;c=496;a=z.Og(this.Ud)!=z.Og(a);b&&(c=PK(this,a?7:5,4,9));c&496&&(c=PK(this,a?6:4,5,9));c&496&&PK(this,a?7:5,4,5)};MK.prototype.qR=z.Il;RK.prototype.S=function(){return this.element.lastChild};z.y(SK,z.yB);var VK={};z.e=SK.prototype;z.e.aj=null;z.e.QA=!1;z.e.Fd=z.hb("AbstractBubblePlugin");z.e.Lt=function(){this.W()&&this.pk();return!1};
z.e.pk=function(a,b){var c;if(a)c=a.target;else if(b)c=b;else{var d=z.aC(this.G);if(d){var f=d.Z(),g=d.ka(),h=d.xa(),k=d.Sa();z.C&&d.isCollapsed()&&f!=g&&(d=z.av(f,h));1==f.nodeType&&f==g&&h==k-1&&(f=f.childNodes[h],1==f.nodeType&&(c=f))}c=c||d&&d.Zb()}var l;a:{if(c){if(d=c)d="IMG"==c.nodeName&&(!!c.getAttribute("eeimg")||z.hj(c,"ee_img"));if(h=d?c:null){if(h!=this.bw||!this.aj)if(this.aj&&WK(this),c=UK(this),!OK(c,this.mz())){this.bw=h;var f=this.mz(),k=this.fH(),g=(0,z.t)(this.WP,this),n=this.vY(),
d=z.pp(),h=new RK(c.ca,d,f,k,h,!n);c.Ld[d]=h;k=0;for(n=c.qo.childNodes.length-1;k<n;k++){var q=c.qo.childNodes[k];if(c.Ld[q.id].type>f){l=q;break}}z.cf(h.element,l||c.qo.lastChild);g(h.S());RJ(h.element,c.U);l=z.fo(c.Ld);1==l?(c.U.g(c.DF,"click",c.EF).g(c.OD,"resize",c.$S).g(c.Qg,"hide",c.FS),c.Qg.F(!0),c.ga()):2==l&&z.ij(c.Ud,"tr_multi_bubble");c.ga();this.aj=d;this.rc.g(c,"hide",this.HH);this.Uf();this.QA&&this.rc.g(c.S(),"keydown",this.nV)}l=!1;break a}}this.aj&&WK(this);l=!1}return l};
z.e.disable=function(a){if(a.Qm==z.MB){var b=VK[a.id];b&&(a==this.G&&WK(this),b.dispose(),delete VK[a.id])}};z.e.mz=function(){return""};z.e.fH=function(){return""};z.e.vY=z.Gl;z.e.Uf=z.r;z.e.FP=z.r;z.e.HH=function(){this.aj=this.bw=null;this.rc.removeAll();this.FP()};z.e.Oz=function(a){if(this.QA&&this.W()&&9==a.keyCode&&!a.shiftKey){var b=UK(this).S();if(b=z.L("tr_bubble_tabbable",b))return b.focus(),a.preventDefault(),!0}return!1};
z.e.nV=function(a){if(this.W()&&9==a.keyCode){var b=UK(this).S(),b=z.Wo("tr_bubble_tabbable",b);(a.shiftKey?b[0]:z.jb(b))==a.target&&(this.G.focus(),a.preventDefault())}};z.e.W=function(){return!!this.aj};z.e.ga=function(){var a=UK(this);a&&a.ga()};
z.e.Os=function(a,b,c,d){b=this.ca.B("SPAN",{className:"tr_bubble_link"},b);this.QA&&(b.hasAttribute("tabindex")||b.setAttribute("tabindex",0),z.ij(b,"tr_bubble_tabbable"));b.setAttribute("role","link");d?d.appendChild(b):(d=this.ca.m(a))&&z.Vo(b,d);b.id=a;RJ(b,this.rc);c&&(a=this.rc,FM.g(b,c,void 0,a.ea||a,a));return b};z.y(YK,SK);var IM=z.w("Equation:"),JM=z.w("Edit"),KM=z.w("Remove");z.e=YK.prototype;z.e.Fd=function(){return"EquationBubble"};z.e.WP=function(a){a.appendChild(a.ownerDocument.createTextNode(IM+" "));this.Os("ee_bubble_edit",JM,this.AQ,a);a.appendChild(a.ownerDocument.createTextNode(IM+" - "));this.Os("ee_remove_remove",KM,this.wX,a)};z.e.mz=function(){return"IMG"};z.e.fH=function(){return z.w("Equation")};z.e.wX=function(){this.G.Ii();z.N(this.bw);WK(this);this.G.Bf()};
z.e.AQ=function(){var a=this.bw;WK(this);this.G.execCommand("+equation",a)};z.y(ZK,z.Lc);ZK.prototype.type="ok";z.y($K,z.Lc);z.y(aL,z.Q);aL.prototype.qk="";aL.prototype.F=function(a){z.P(this.m(),a)};z.y(bL,z.jF);z.e=bL.prototype;z.e.Si=function(){return this.hb};z.e.mm=function(a){return 0<=a&&a<this.Xn.length?this.Xn[a]:null};z.e.Mf=function(a){bL.v.Mf.call(this,a);this.Og.dispatchEvent(new dL(LM,this))};z.e.ym=function(a){bL.v.ym.call(this,a);a.relatedTarget&&!z.nf(this.m(),a.relatedTarget)&&this.Og.Ts()};z.e.Gd=function(a){bL.v.Gd.call(this,a);a.relatedTarget&&!z.nf(this.m(),a.relatedTarget)&&this.Og.ty.stop()};var LM="a";dL.prototype.vz=function(){return this.LW};z.y(cL,z.bF);z.ka(cL);
cL.prototype.V=function(){return"ee-palette"};z.y(eL,aL);z.e=eL.prototype;z.e.aJ="";z.e.Tx=0;
z.e.B=function(){var a=z.w("TeX 公式"),b=z.w("预览"),c=z.w("了解更多"),d=this.ca,c=d.B("DIV",{style:"display: none;"},d.B("SPAN",{"class":"ee-section-title ee-section-title-floating"},a),this.qk?d.B("A",{id:"ee-section-learn-more",target:"_blank",href:this.qk},c):null,d.B("DIV",{style:"clear: both;"}),a=this.FT=d.B("DIV",{style:"position: relative"}));this.Og.setActive("mn").render(a);a.appendChild(d.B("DIV",{style:"clear:both"}));var f=this.gi=d.B("textarea",{"class":"ee-tex",dir:"ltr"});a.appendChild(f);
a.appendChild(d.B("DIV",{"class":"ee-section-title"},b));b=this.cX=d.B("DIV",{"class":"ee-preview-container"});a.appendChild(b);this.h=c};z.e.C=function(){this.eM=new z.GE(this.gi);z.G(this.eM,"input",this.JH,!1,this);this.o().g(this.gi,"keydown",this.JH);this.o().g(this.Og,LM,this.ES)};z.e.F=function(a){eL.v.F.call(this,a);a&&z.vd(this.ZQ,0,this)};z.e.ZQ=function(){this.gi.focus();z.Ls(this.gi,this.gi.value.length)};z.e.JH=function(){this.Tx++;z.vd((0,z.t)(this.PS,this,this.Tx),500)};
z.e.PS=function(a){a==this.Tx&&fL(this)};z.e.ES=function(a){var b=a.vz(),c=this.Og,d=c.Yn;a=this.gi;if("mn"==b.Si()){var f=b.$a,f=-1!=f?b.mm(f):null;if(d!=b&&d.Si()==f){c.wH();return}f&&(b=this.Og.setActive(f),b.m()||b.render(this.FT),b=b.m(),z.Bg(b,0,-b.clientHeight))}else{d=this.Og.Yn;f=d.mm(d.$a);if(!f)return;z.vd((0,z.t)(this.MT,this,f+" "),0)}a.focus()};z.e.MT=function(a){var b=this.gi,c=z.Is(b)[0],d=b.value,d=d.substring(0,c)+a+d.substring(c);b.value=d;z.Ls(b,c+a.length);fL(this)};z.e.qm=function(){return this.gi.value};
z.e.HC=function(a){this.gi.value=a;fL(this)};z.e.D=function(){this.eM.dispose();this.Og=null;eL.v.D.call(this)};z.y(gL,z.Q);z.e=gL.prototype;z.e.hi=null;z.e.B=function(){gL.v.B.call(this);this.Ms()};z.e.Ms=function(){var a=this.m();this.hi=new eL(this.NF,this.qk,this.ca);this.K(this.hi);this.hi.render(a);this.hi.F(!0)};z.e.T=function(a){this.h=a;this.Ms()};z.e.qm=function(){return this.hi.qm()};z.e.HC=function(a){this.hi.HC(a)};z.e.uz=function(){var a=this.qm(),b=XK(a);return b?'\x3cimg src\x3d"'+b+'" alt\x3d"'+z.Ma(a)+'" class\x3d"ee_img tr_noresize" eeimg\x3d"1" style\x3d"vertical-align: middle"\x3e':""};
z.e.isValid=function(){return 1024<this.qm().length};z.e.F=function(a){this.hi.F(a)};z.e.D=function(){this.hi&&this.hi.dispose();this.NF=null;gL.v.D.call(this)};z.y(hL,z.TE);hL.prototype.hy=function(){var a=new z.UE(this),b=z.w("公式编辑器"),c=z.w("插入公式"),d=z.w("保存修改"),f=z.w("取消"),c=this.$j.qm()?d:c;z.VE(z.WE(a.La(b).aa(this.$j.m()),f),c);return z.XE(a)};hL.prototype.Do=function(){if(this.$j.isValid())return null;var a=this.$j.uz();return new ZK(a)};hL.prototype.zB=function(a){this.SJ||(this.SJ=this.wt("ok"));this.SJ.disabled=!a.isValid};z.y(iL,bL);z.y(jL,bL);z.y(kL,bL);z.y(lL,bL);z.y(mL,bL);mL.prototype.F=function(a,b){return mL.v.F.call(this,!0,b)};z.y(nL,cL);z.ka(nL);nL.prototype.V=function(){return"ee-menu-palette"};z.y(oL,bL);z.y(pL,z.H);z.e=pL.prototype;z.e.vz=function(a){var b=this.yK,c=b[a];if(!c){switch(a){case "mn":c=new mL(this);break;case "g":c=new kL(this);break;case "s":c=new oL(this);break;case "c":c=new jL(this);break;case "m":c=new lL(this);break;case "a":c=new iL(this);break;default:throw Error("Invalid palette type!");}b[a]=c}return c};z.e.setActive=function(a){var b=this.Yn;b&&b.F(!1);this.Yn=b=this.vz(a);b.F(!0);return b};z.e.Ts=function(){this.ty.start()};z.e.wH=function(){this.setActive("mn")};
z.e.L=function(){return this.yQ};z.e.D=function(){pL.v.D.call(this);this.yK=this.Yn=null};z.y(qL,z.YE);z.e=qL.prototype;z.e.Fd=z.hb("EquationEditorPlugin");z.e.gy=function(a,b){var c=b||null,d;c?(d=c.getAttribute("alt"),d||(d=(d=c.getAttribute("src"))?z.be(d,"tex")||"":"")):d="";this.wK=c;c={};c.KW=new pL(a);c=new hL(c,a,d,this.qk);c.addEventListener("ok",this.jp,!1,this);return c};z.e.enable=function(a){qL.v.enable.call(this,a);this.isEnabled(a)&&(this.fQ=z.G(a.m(),"dblclick",(0,z.t)(this.OR,this),!1,this))};z.e.disable=function(a){qL.v.disable.call(this,a);this.isEnabled(a)||z.nd(this.fQ)};
z.e.OR=function(a){(a=a.target)&&"IMG"===a.nodeName&&a.getAttribute("eeimg")&&this.execCommand("+equation",a)};z.e.jp=function(a){z.ZE(this);this.G.Ii();a=z.Ze(z.zB(this).Ra,a.OQ);if(this.wK)z.Vo(a,this.wK);else{var b=z.aC(this.G);b.isCollapsed()||b.Xf();a=b.insertNode(a,!1)}z.rv(a,!1);this.G.Bf()};z.y(rL,z.yB);rL.prototype.Mt=function(a){return z.B&&this.G.Eh?!1:9!=a.keyCode||a.metaKey||a.ctrlKey?!1:tL(this,a)};z.y(sL,rL);sL.prototype.Fd=function(){return"ListTabHandler"};z.y(uL,z.yB);z.e=uL.prototype;z.e.Fd=z.hb("LoremIpsum");z.e.$r=z.Hl;z.e.Dr=!1;z.e.queryCommandValue=function(a){return"usinglorem"==a&&this.Dr};
z.e.execCommand=function(a,b){if("clearlorem"==a){var c=!!b,d=this.G;if(this.Dr&&!d.Eh){var f=d.m();f||(f=d.Wc);this.Dr=!1;f.style.fontStyle=this.aV;d.he(!0,null,!0);c&&d.Kc()&&(z.D?(z.Ke(d.m()).body.focus(),d.wg()):z.wg&&z.gC(d))}}else"updatelorem"==a&&(c=this.G,this.Dr||c.Eh||z.wH==c.id||((d=c.m())||(d=c.Wc),z.iv(d)&&(this.Dr=!0,this.aV=d.style.fontStyle,d.style.fontStyle="italic",c.he(!0,this.OU,!0))))};z.e.ef=function(a){return"clearlorem"==a||"updatelorem"==a||"usinglorem"==a};z.y(vL,z.H);z.y(wL,z.H);z.e=wL.prototype;z.e.au=null;z.e.zD=function(){xL(this,this.je,this.Zk)};z.e.lC=function(){xL(this,this.Zk,this.je)};z.e.qh=function(){if(!this.au&&0!=this.jv.length){var a=this.jv.shift();this.dispatchEvent({type:a.type,state:a.state})&&(a.state.XO?(this.au=z.G(a.state,"action_completed",this.UQ,!1,this),a.cH.call(a.state)):(a.cH.call(a.state),this.qh()))}};z.e.UQ=function(){z.nd(this.au);this.au=null;this.qh()};z.y(yL,z.yB);yL.prototype.up=null;var MM=z.fp({V_:"+undo",K_:"+redo"});z.e=yL.prototype;z.e.ef=function(a){return a in MM};z.e.BM=function(a){this.disable(a);this.G=null};z.e.enable=function(a){if(!this.isEnabled(a)){z.dC(a);var b=new z.xd(this);z.B||b.g(a,"beforechange",this.zR);b.g(a,z.IB,this.JR);b.g(a,"blur",this.Cz);this.ak[a.Ch]=b;zL(this,a)}};z.e.disable=function(a){z.dC(a);var b=this.ak[a.Ch];b&&(b.dispose(),delete this.ak[a.Ch]);this.Io[a.Ch]&&delete this.Io[a.Ch]};z.e.isEnabled=function(a){return!!this.ak[a.Ch]};
z.e.D=function(){yL.v.D.call(this);for(var a in this.ak)this.ak[a].dispose(),delete this.ak[a];this.G=null;this.fg&&(this.fg.dispose(),delete this.fg)};z.e.Fd=function(){return"UndoRedo"};z.e.execCommand=function(a){"+undo"==a?this.fg.zD():"+redo"==a&&this.fg.lC()};z.e.queryCommandValue=function(a){var b=null;"+undo"==a?b=0<this.fg.je.length:"+redo"==a&&(b=0<this.fg.Zk.length);return b};z.e.uQ=function(){this.G.dispatchEvent({type:"cvc",OP:["+redo","+undo"]})};
z.e.LX=function(a,b,c){var d=this.G;if(d){z.cC(d,!0,!0);try{d.Ii();d.execCommand("clearlorem",!0);z.mv(d.m(),b);c&&c.select();var f=this.G;d.focus();f&&f.Ch!=a.Po&&f.execCommand("updatelorem");var g=this.Io[a.Po];g.rj=b;g.yM=c}catch(h){}finally{this.up=a,d.Bf(),z.bC(d)}}};
z.e.Mt=function(a,b,c){if(c){var d;"z"==b?d=a.shiftKey?"+redo":"+undo":"y"==b&&(d="+redo");if(d)return"+undo"==d?(a=this.fg,a=a.je[a.je.length-1]):(a=this.fg,a=a.Zk[a.Zk.length-1]),a&&a.Po?this.G.execCommand(d):this.execCommand(d),!0}return!1};z.e.zR=function(a){if(!this.up){a=a.target;var b=a.Ch;this.sI!=b&&(this.sI=b,zL(this,a))}};z.e.JR=function(a){this.up?(a=this.up,this.up=null,a.dispatchEvent("action_completed")):zL(this,a.target)};z.e.Cz=function(a){(a=a.target)&&z.dC(a)};z.y(BL,vL);
BL.prototype.zD=function(){this.jL(this,this.rj,this.yM)};BL.prototype.lC=function(){this.jL(this,this.mC,this.pX)};BL.prototype.equals=function(a){return this.Po==a.Po&&this.rj==a.rj&&this.mC==a.mC};AL.prototype.isValid=function(){return this.ou};AL.prototype.toString=function(){return z.NG?"W3C:"+this.Ea.toString()+"\n"+this.ZC+":"+this.Ca.toString()+"\n"+this.My:"IE:"+this.Ea+","+this.Ca};AL.prototype.select=function(){var a=this.Xe(this.ue.m());a&&(z.MG&&this.ue.m().focus(),z.Zu(a).select())};
AL.prototype.Xe=function(a){if(z.NG){var b=FK(this.Ea,a);a=FK(this.Ca,a);return b&&a?z.Iu(b,this.ZC,a,this.My).we():null}b=a.ownerDocument.body.createTextRange();b.moveToElementText(a);b.collapse(!0);b.moveEnd("character",this.Ca);b.moveStart("character",this.Ea);return b};z.y(DL,z.H);z.e=DL.prototype;z.e.o=function(){return this.ea};z.e.qz=function(){return this.ue};z.e.W=function(){return this.Nb.W()};z.e.F=function(a){this.Nb.F(a)};z.e.isEnabled=function(){return this.Nb.isEnabled()};z.e.gb=function(a){this.Nb.gb(a)};z.e.blur=function(){this.Nb.od(null)};z.e.D=function(){DL.v.D.call(this);this.ea&&(this.ea.dispose(),delete this.ea);this.Nb&&(this.Nb.dispose(),delete this.Nb);delete this.ue;delete this.fC};
z.e.GZ=function(a){if(this.Nb.isEnabled()&&this.dispatchEvent("change")){var b;try{b=this.ue.queryCommandValue(a.OP||this.fC)}catch(f){b={}}a=b;for(var c in a)if(b=z.ah(this.Nb,c)){var d=a[c];b.tj?b.tj(d):b.yc(!!d)}}};z.e.uR=function(a){var b=a.target.xe();this.ue.execCommand(b,a.target.X())};z.y(FL,z.mA);z.cq("goog-toolbar-separator",function(){return new FL});z.y(GL,z.yB);z.e=GL.prototype;z.e.defaults={D0:z.r};z.e.Fd=z.hb("FastUpload");
z.e.enable=function(a){if(!this.isEnabled(a)&&(window.URL||window.webkitURL)&&window.FileReader&&window.FormData&&window.document.addEventListener){window.$.fn.draghover=function(){return this.each(function(){var a=(0,window.$)(),b=(0,window.$)(this),f=!0;b.on("dragenter",function(g){g=g.originalEvent;0===a.size()&&f&&z.rb(g.dataTransfer.types,"Files")&&b.trigger("draghoverstart",g);a=a.add(g.target)});b.on("dragleave",function(g){(0,window.setTimeout)(function(){a=a.not(g.target);0===a.size()&&f&&
b.trigger("draghoverend",g)},1)});b.on("dragstart",function(){f=!1});b.on("drop dragend",function(){a=(0,window.$)();b.trigger("draghoverend");f=!0})})};this.YD=(0,window.$)(this.G.m());var b=this.mN=HL(this);new z.xd(this);a.m().addEventListener("paste",(0,z.t)(this.Qz,this));window.document.addEventListener("dragover",(0,z.t)(this.YR,this),!1);b.on("dragover",(0,z.t)(this.XR,this));b.get(0).addEventListener("drop",(0,z.t)(this.Jt,this),!1);(0,window.$)(window).draghover().on({draghoverstart:(0,z.t)(this.yH,
this),draghoverend:(0,z.t)(this.ZR,this)});b.draghover().on({draghoverstart:(0,z.t)(this.QR,this),draghoverend:(0,z.t)(this.yH,this)})}};z.e.YR=function(a){z.rb(a.dataTransfer.types,"Files")&&(a.dataTransfer.dropEffect="none",a.preventDefault())};z.e.XR=function(a){a=a.originalEvent;a.dataTransfer.dropEffect="copy";a.preventDefault();a.stopPropagation()};z.e.yH=function(a){a.preventDefault();a.stopPropagation();JL(this,1)};z.e.QR=function(a){JL(this,2);a.stopPropagation()};
z.e.ZR=function(a){a.preventDefault();JL(this,0)};z.e.Qz=function(a){var b=this;a.clipboardData&&z.rb(a.clipboardData.types,"Files")&&1===a.clipboardData.items.length&&z.A(a.clipboardData.items,function(c){-1<c.type.indexOf("image")&&(KL(b,c.getAsFile()),a.preventDefault())})};
z.e.Jt=function(a){var b=this;b.G.execCommand("clearlorem");var c=a.dataTransfer.files;a.preventDefault();var d=[];z.A(c,function(a){-1<a.type.indexOf("image")?(KL(b,a),d.push(!0)):d.push(!1)});z.go(d,function(a){return!a})&&z.W.message("文件类型不支持！");JL(b,0)};var NM={};
(function(){function a(a,c,d){function q(a){z.ff(a)}function ca(b,c){for(;b!==a;){if(c(b))return b;b=b.parentNode}return null}function Va(a){return a.tagName&&a.tagName===c}if(!a)throw"Missing Editable Container";c||(c="blockquote");c=c.toUpperCase();var Sa=z.Xu();if(function(b){return b&&g(a,z.fu(b))&&g(a,z.hu(b))}(Sa)){var Aa=h(Sa),ua=k(Sa),Jd=Sa.Zb(),wi=ca(Jd,Va),we=z.nb(ua,function(a,b){1===b.nodeType&&(Va(b)?a.push(b):a.push.apply(a,z.vb(b.getElementsByTagName(c))));return a},[]),Ud;if(wi){if(d)return n.Xw;
z.ff(wi)}else if(we.length){if(d)return n.Xw;z.A(we,q)}else{if(d)return n.tE;if(d=ca(Jd,function(a){return z.rb(l,a.tagName.toLowerCase())}))Ud=window.document.createElement(c),d.parentNode.insertBefore(Ud,d),Ud.appendChild(d);else if(Sa.Z()!==Sa.ka())Ud=window.document.createElement(c),ua[0].parentNode.insertBefore(Ud,ua[0]),z.A(ua,function(a){Ud.appendChild(a)});else return f(a,c)}b(a,Aa)}else if(d)return n.tE}function b(a,b){if(b){var c=function(b,c){return b&&g(a,b)&&z.kv(b)>=c};c(b.Z(),b.xa())&&
c(b.ka(),b.Sa())&&b.select()}}function c(a){return a&&"BR"===a.tagName||UJ(a)||z.ov(a)}function d(a){a=z.wf(a,function(a){a=a.parentNode;return UJ(a)||z.ov(a)},!0);var b=WJ(new z.cv(a,!0,!0),z.kp(c));a=WJ(new z.cv(a,!1,!1),z.kp(c));return z.Pd(b).reverse().concat(z.Pd(a))}function f(a,b){if(q.eO)window.document.execCommand("formatBlock",!1,b);else{var c=z.Xu(),f=c.Ic();if(z.lf(f)&&z.iv(f))c=window.document.createElement(b),f===a?f.appendChild(c):z.Vo(c,f),(z.D||z.B)&&c.appendChild(window.document.createElement("br")),
z.qv(c);else if(f=c.ka(),f=d(f),f.length){var c=window.document.createElement(b),g=z.jb(f),h=g.nextSibling;h&&h&&"BR"===h.tagName&&z.N(h);z.df(c,g);z.af(c,f);(z.D||z.B)&&c.appendChild(window.document.createElement("br"));z.rv(c.lastChild)}}}function g(a,b){return 3===a.nodeType?a===b:a.contains(3===b.nodeType?b.parentNode:b)}function h(a){return JJ(a.Z(),a.xa(),a.ka(),a.Sa())}function k(a){function b(a){return!(a.previousSibling&&g(a.previousSibling,h))}function c(a){return f!==d&&!g(a,f)}if(a.isCollapsed())return[];
var d=a.Ic(),f=a.Z(),h=a.ka();a=d.childNodes;return z.Pd(1===a.length?a:WJ(XJ(a,c),b))}var l=["ul","ol","dl","table"],n={Xw:1,tE:0},q=NM;q.eO=!z.C;q.toggle=a;q.getState=function(b,c){return a(b,c,!0)};q.$N=n})();z.y(LL,z.yB);z.e=LL.prototype;z.e.Fd=z.hb("Blockquote");z.e.ef=function(a){return"+blockquote"===a};z.e.Df=function(a){this.ef(a)&&NM.toggle(this.G.m())};z.e.queryCommandValue=function(){return NM.$N.Xw===NM.getState(this.G.m())};z.e.Oz=function(a){if(13===a.keyCode)return this.Kz(a)};z.e.NC=function(a,b){return NL(a,b).NC};
z.e.Kz=function(a){var b=z.aC(this.G);if(b.isCollapsed()){var c;a:{c=b.ka();for(var d=this.G.Ka;c!==d;){if("BLOCKQUOTE"===c.tagName)break a;c=c.parentNode}c=void 0}if(c&&(b=NL(c,b),b.NC)){a.preventDefault();a=window.document.createElement("div");z.df(a,c);if(z.D||z.B)c=c.nextSibling,(c=ML(c)&&c)||(c=window.document.createElement("br")),a.appendChild(c);z.av(a,0).select();b.OJ&&z.N(b.OJ)}}};z.tI["+blockquote"]={tb:!0,na:"引用内容",Ba:"+blockquote",Wa:"tr-icon tr-blockquote",factory:z.YF};z.y(PL,z.Q);
var SL=[["ABAP","abap"],["ABNF","abnf"],["ActionScript 3","as3"],["ActionScript","as"],["Ada","ada"],["ADL","adl"],["Agda","agda"],["Alloy","alloy"],["AmbientTalk","at"],["ANTLR","antlr"],["ApacheConf","apacheconf"],["APL","apl"],["AppleScript","applescript"],["Arduino","arduino"],["AspectJ","aspectj"],["aspx-cs","aspx-cs"],["aspx-vb","aspx-vb"],["Asymptote","asy"],["autohotkey","ahk"],["AutoIt","autoit"],["Awk","awk"],["Base Makefile","basemake"],["Bash Session","console"],["Bash","bash"],["Batchfile",
"bat"],["BBCode","bbcode"],["BC","bc"],["Befunge","befunge"],["BlitzBasic","blitzbasic"],["BlitzMax","blitzmax"],["BNF","bnf"],["Boo","boo"],["Boogie","boogie"],["Brainfuck","brainfuck"],["Bro","bro"],["BUGS","bugs"],["C","c"],["C#","csharp"],["C++","cpp"],["c-objdump","c-objdump"],["ca65 assembler","ca65"],["cADL","cadl"],["CAmkES","camkes"],["CBM BASIC V2","cbmbas"],["Ceylon","ceylon"],["CFEngine3","cfengine3"],["cfstatement","cfs"],["ChaiScript","chai"],["Chapel","chapel"],["Cheetah","cheetah"],
["Cirru","cirru"],["Clay","clay"],["Clojure","clojure"],["ClojureScript","clojurescript"],["CMake","cmake"],["COBOL","cobol"],["COBOLFree","cobolfree"],["CoffeeScript","coffee-script"],["Coldfusion CFC","cfc"],["Coldfusion HTML","cfm"],["Common Lisp","common-lisp"],["Component Pascal","componentpascal"],["Coq","coq"],["cpp-objdump","cpp-objdump"],["CPSA","cpsa"],["Crmsh","crmsh"],["Croc","croc"],["Cryptol","cryptol"],["Csound Document","csound-document"],["Csound Orchestra","csound"],["Csound Score",
"csound-score"],["CSS","css"],["CUDA","cuda"],["Cypher","cypher"],["Cython","cython"],["D","d"],["d-objdump","d-objdump"],["Darcs Patch","dpatch"],["Dart","dart"],["Debian Control file","control"],["Debian Sourcelist","sourceslist"],["Delphi","delphi"],["dg","dg"],["Diff","diff"],["Django/Jinja","django"],["Docker","docker"],["DTD","dtd"],["Duel","duel"],["Dylan session","dylan-console"],["Dylan","dylan"],["DylanLID","dylan-lid"],["Earl Grey","earl-grey"],["Easytrieve","easytrieve"],["EBNF","ebnf"],
["eC","ec"],["ECL","ecl"],["Eiffel","eiffel"],["Elixir iex session","iex"],["Elixir","elixir"],["Elm","elm"],["EmacsLisp","emacs"],["Embedded Ragel","ragel-em"],["ERB","erb"],["Erlang erl session","erl"],["Erlang","erlang"],["Evoque","evoque"],["Ezhil","ezhil"],["Factor","factor"],["Fancy","fancy"],["Fantom","fan"],["Felix","felix"],["Fish","fish"],["Fortran","fortran"],["FortranFixed","fortranfixed"],["FoxPro","foxpro"],["FSharp","fsharp"],["GAP","gap"],["GAS","gas"],["Genshi Text","genshitext"],
["Genshi","genshi"],["Gettext Catalog","pot"],["Gherkin","cucumber"],["GLSL","glsl"],["Gnuplot","gnuplot"],["Go","go"],["Golo","golo"],["GoodData-CL","gooddata-cl"],["Gosu Template","gst"],["Gosu","gosu"],["Groff","groff"],["Groovy","groovy"],["Haml","haml"],["Handlebars","handlebars"],["Haskell","haskell"],["Haxe","hx"],["Hexdump","hexdump"],["HTML","html"],["HTML+Django/Jinja","html+django"],["HTML+Handlebars","html+handlebars"],["HTTP","http"],["Hxml","haxeml"],["Hy","hylang"],["Hybris","hybris"],
["IDL","idl"],["Idris","idris"],["Igor","igor"],["Inform 6 template","i6t"],["Inform 6","inform6"],["Inform 7","inform7"],["INI","ini"],["Io","io"],["Ioke","ioke"],["IRC logs","irc"],["Isabelle","isabelle"],["J","j"],["Jade","jade"],["JAGS","jags"],["Jasmin","jasmin"],["Java Server Page","jsp"],["Java","java"],["JavaScript","js"],["JCL","jcl"],["JSON","json"],["JSON-LD","jsonld"],["Julia console","jlcon"],["Julia","julia"],["Kal","kal"],["Kconfig","kconfig"],["Koka","koka"],["Kotlin","kotlin"],["Lasso",
"lasso"],["Lean","lean"],["LessCss","less"],["Lighttpd configuration file","lighty"],["Limbo","limbo"],["liquid","liquid"],["Literate Agda","lagda"],["Literate Cryptol","lcry"],["Literate Haskell","lhs"],["Literate Idris","lidr"],["LiveScript","live-script"],["LLVM","llvm"],["Logos","logos"],["Logtalk","logtalk"],["LSL","lsl"],["Lua","lua"],["Makefile","make"],["Mako","mako"],["MAQL","maql"],["Mask","mask"],["Mason","mason"],["Mathematica","mathematica"],["Matlab session","matlabsession"],["Matlab",
"matlab"],["MiniD","minid"],["Modelica","modelica"],["Modula-2","modula2"],["MoinMoin/Trac Wiki markup","trac-wiki"],["Monkey","monkey"],["MOOCode","moocode"],["MoonScript","moon"],["mozhashpreproc","mozhashpreproc"],["mozpercentpreproc","mozpercentpreproc"],["MQL","mql"],["Mscgen","mscgen"],["MSDOS Session","doscon"],["MuPAD","mupad"],["MXML","mxml"],["Myghty","myghty"],["MySQL","mysql"],["NASM","nasm"],["Nemerle","nemerle"],["nesC","nesc"],["NewLisp","newlisp"],["Newspeak","newspeak"],["Nginx configuration file",
"nginx"],["Nimrod","nimrod"],["Nit","nit"],["Nix","nixos"],["NSIS","nsis"],["NumPy","numpy"],["objdump","objdump"],["objdump-nasm","objdump-nasm"],["Objective-C","objective-c"],["Objective-C++","objective-c++"],["Objective-J","objective-j"],["OCaml","ocaml"],["Octave","octave"],["ODIN","odin"],["Ooc","ooc"],["Opa","opa"],["OpenEdge ABL","openedge"],["PacmanConf","pacmanconf"],["Pan","pan"],["ParaSail","parasail"],["Pawn","pawn"],["Perl","perl"],["Perl6","perl6"],["PHP","php"],["Pig","pig"],["Pike",
"pike"],["PkgConfig","pkgconfig"],["PL/pgSQL","plpgsql"],["PostgreSQL console (psql)","psql"],["PostgreSQL SQL dialect","postgresql"],["PostScript","postscript"],["POVRay","pov"],["PowerShell Session","ps1con"],["PowerShell","powershell"],["Praat","praat"],["Prolog","prolog"],["Properties","properties"],["Protocol Buffer","protobuf"],["Puppet","puppet"],["PyPy Log","pypylog"],["Python 3","python3"],["Python 3.0 Traceback","py3tb"],["Python console session","pycon"],["Python Traceback","pytb"],["Python",
"python"],["QBasic","qbasic"],["QML","qml"],["QVTO","qvto"],["Racket","racket"],["Ragel","ragel"],["RConsole","rconsole"],["Rd","rd"],["REBOL","rebol"],["Red","red"],["Redcode","redcode"],["reg","registry"],["ResourceBundle","resource"],["reStructuredText","rst"],["Rexx","rexx"],["RHTML","rhtml"],["Roboconf Graph","roboconf-graph"],["Roboconf Instances","roboconf-instances"],["RobotFramework","robotframework"],["RPMSpec","spec"],["RQL","rql"],["RSL","rsl"],["Ruby irb session","rbcon"],["Ruby","rb"],
["Rust","rust"],["S","splus"],["Sass","sass"],["Scala","scala"],["Scalate Server Page","ssp"],["Scaml","scaml"],["Scheme","scheme"],["Scilab","scilab"],["SCSS","scss"],["Shen","shen"],["Slim","slim"],["Smali","smali"],["Smalltalk","smalltalk"],["Smarty","smarty"],["Snobol","snobol"],["SourcePawn","sp"],["SPARQL","sparql"],["SQL","sql"],["sqlite3con","sqlite3"],["SquidConf","squidconf"],["Stan","stan"],["Standard ML","sml"],["SuperCollider","sc"],["Swift","swift"],["SWIG","swig"],["systemverilog",
"systemverilog"],["TADS 3","tads3"],["TAP","tap"],["Tcl","tcl"],["Tcsh Session","tcshcon"],["Tcsh","tcsh"],["Tea","tea"],["Termcap","termcap"],["Terminfo","terminfo"],["Terraform","terraform"],["TeX","tex"],["Text only","text"],["Thrift","thrift"],["Todotxt","todotxt"],["TrafficScript","rts"],["Treetop","treetop"],["Turtle","turtle"],["Twig","twig"],["TypeScript","ts"],["UrbiScript","urbiscript"],["Vala","vala"],["VB.net","vb.net"],["VCTreeStatus","vctreestatus"],["Velocity","velocity"],["verilog",
"verilog"],["VGL","vgl"],["vhdl","vhdl"],["VimL","vim"],["X10","x10"],["XML","xml"],["XQuery","xquery"],["XSLT","xslt"],["Xtend","xtend"],["XUL+mozpreproc","xul+mozpreproc"],["YAML","yaml"],["YAML+Jinja","yaml+jinja"],["Zephir","zephir"]],UL=z.mb(SL,QL);z.e=PL.prototype;z.e.defaults={gY:"lang-select",Es:"collapsed",sU:"lang-list",AW:"lang-option",jh:"active",zF:"checked"};z.e.D=function(){PL.v.D.call(this);this.o().dispose();this.Y.dispose();z.N(this.h);this.qt=this.gw=this.h=null};
z.e.B=function(){var a=this.J;this.h=z.M("div",{innerHTML:this.template,className:[a.gY,a.Es].join(" ")})};z.e.template='\x3cdiv class\x3d"title-button"\x3e选择语言\x3c/div\x3e\x3ci class\x3d"zg-icon zg-icon-double-arrow"\x3e\x3c/i\x3e\x3cdiv class\x3d"input-wrapper"\x3e\x3cinput class\x3d"filter-input zg-form-text-input" placeholder\x3d"搜索语言"\x3e\x3c/div\x3e';
z.e.C=function(){PL.v.C.call(this);this.gw=z.L("title-button",this.h);this.qt=z.L("filter-input",this.h);z.Fo(this.gw,!0);VL(this,this.qt,this.h);this.o().g(this.h,"click",this.vm).g(this.gw,"click",this.QS)};z.e.X=function(){return this.Ie};z.e.Da=function(a){var b=a&&z.pb(UL,function(b){return b.value===a});b&&(this.bl(b.label),this.dispatchEvent({type:"change",zW:b}));this.Ie=a};
z.e.vm=function(a){var b=this.Y,c=b.M.m();c&&window.document.activeElement!==this.qt&&!c.contains(a.target)&&(a.preventDefault(),a.stopPropagation(),z.Gs(b))};z.e.QS=function(){this.isCollapsed()&&this.lj(!1)};z.e.vt=function(){return this.Y};z.e.isCollapsed=function(){return z.V.has(this.h,this.J.Es)};z.e.lj=function(a){if(this.isCollapsed()!==a){var b=this.qt,c=this.J;a?z.V.add(this.h,c.Es):(z.V.remove(this.h,c.Es),a=this.Y,c=a.M,a.kn(UL),c.m().scrollTop=0,c.show(),b.value="",b.focus())}};
z.e.bl=function(a){var b=this.gw;b.title=a;z.of(b,a)};z.e.GB=function(a){this.Da(a.value);this.Y.Rc()};z.y(WL,z.yB);var iM=z.D||z.wg||z.B;z.e=WL.prototype;z.e.Fd=z.hb("CodePlugin");z.e.ef=function(a){return"+code"===a};z.e.Df=function(a){this.ef(a)&&this.trigger()};z.e.queryCommandValue=function(){var a="1"===dM(this).state,b=this.G.bc.EnterHandler;b&&(a?b.disable(this.G):b.enable(this.G));bM(this,a);return a};z.e.defaults={gQ:""};z.e.qY=function(a){this.Nb=a;this.Uy=["toggleFullScreen"].concat("+code")};z.e.D=function(){WL.v.D.call(this);this.Nb=null};
z.e.trigger=function(){var a=dM(this),b=a.vv,c=a.code;switch(a.state){case "1":var d=!(0,z.ab)(z.Oo(c)),a=z.hv(c);d?(c.parentNode.removeChild(c),a&&z.rv(a,!0)):(b=KJ(b),d=z.La(c.innerHTML),z.fv(z.dp(new z.cv(c,!1,!0),z.gv))&&(d="\x3cbr\x3e"+d),a&&"BR"!==a.tagName&&(d+="\x3cbr\x3e"),a=z.Ye(d),c.parentNode.replaceChild(a,c),b.restore());break;case "2":c=lM,a=(0,z.ab)(b.ae())?aM(b.Bg()):iM?"\n":"",c(this,b,a)}};
z.e.Bo=function(a,b){var c=window.document.createElement(a);c.id=z.Yg(z.Xg.ba());return b(c,function(){c=z.J(c.id);c.removeAttribute("id");return c})};z.e.ih=function(){var a=this.G;this.Wn=$L(this.G.Ka);z.Ac(a,this.Wn);z.G(a,"delayedchange",this.GX,!1,this);z.G(a.Ka,"paste",this.Qz,!1,this)};z.e.GX=function(){var a=this.Wn&&this.Wn.tz();a&&a.W()&&a.anchor&&a.ga()};
z.e.Qz=function(a){var b=dM(this),c=b.vv,d=b.code;if("1"===b.state)if(b=a.sc.clipboardData)b.types&&z.rb(b.types,"text/plain")&&(a.preventDefault(),b=b.getData("text/plain"),eM(c,b));else if(window.clipboardData){if(b=window.clipboardData.getData("Text"))a.preventDefault(),fM(this,c,b)}else{var f=c.xa();a=c.ae().length;var g=(d.firstChild?z.kv(d.firstChild):0)-f-a;(0,window.setTimeout)(function(){var a=aM(d.innerHTML);z.of(d,a);a=(d.firstChild?z.kv(d.firstChild):0)-g;d.firstChild&&z.av(d.firstChild,
Math.max(f,a)).select()})}};z.e.Oz=function(a){if(13===a.keyCode)return this.Kz(a);if(40===a.keyCode)return hM(this)};z.e.Kz=function(a){var b=dM(this),c=b.vv;if("1"===b.state)return a.preventDefault(),z.C?kM(this,c):window.document.queryCommandSupported("insertLineBreak")?window.document.execCommand("insertLineBreak"):(a=window.document.createTextNode("\n"),c.insertNode(a),z.rv(a)),this.G.Bf(),!0};z.tI["+code"]={tb:!0,na:"插入代码",Ba:"+code",Wa:"tr-icon tr-code",factory:z.YF};z.y(nM,z.yB);var OM=/^(DIV|TR|LI|BLOCKQUOTE|H\d|PRE|XMP)/;z.e=nM.prototype;z.e.Fd=function(){return"RemoveFormatting"};z.e.ef=function(a){return"+removeFormat"==a};z.e.Df=function(a){"+removeFormat"==a&&pM(this)};z.e.Mt=function(a,b,c){return c?" "==b?(this.G.execCommand("+removeFormat"),!0):!1:!1};
z.e.$K=function(a){var b=window.document.createElement("DIV");b.innerHTML=a;a=[];for(var b=[b.childNodes,0],c=[],d=0,f=[],g=0,h=0;0<=h;h-=2){for(var k=!1;0<g&&h<=f[g-1];)g--,k=!0;k&&oM(a);for(k=!1;0<d&&h<=c[d-1];)d--,k=!0;k&&oM(a);for(var k=b[h],l=b[h+1];l<k.length;){var n=k[l++],q=n.nodeName,v=this.qH(n);if(null!=v)a.push(v);else{switch(q){case "#text":n=0<d?n.nodeValue:z.tp(n.nodeValue);n=z.Ma(n);a.push(n);continue;case "P":oM(a);oM(a);break;case "BR":oM(a);continue;case "TABLE":oM(a);f[g++]=h;
break;case "PRE":case "XMP":c[d++]=h;break;case "STYLE":case "SCRIPT":case "SELECT":continue;case "A":if(n.href&&""!=n.href){a.push("\x3ca href\x3d'");a.push(n.href);a.push("'\x3e");a.push(this.$K(n.innerHTML));a.push("\x3c/a\x3e");continue}else break;case "IMG":a.push("\x3cimg src\x3d'");a.push(n.src);a.push("'");"0"==n.border&&a.push(" border\x3d'0'");a.push("\x3e");continue;case "TD":n.previousSibling&&a.push(" ");break;case "TR":n.previousSibling&&oM(a);break;case "DIV":if(v=n.parentNode,v.firstChild==
n&&OM.test(v.tagName))break;default:OM.test(q)&&oM(a)}n=n.childNodes;0<n.length&&(b[h++]=k,b[h++]=l,k=n,l=0)}}}return a.join("").replace(/\xa0|[ \t]+/g," ")};z.e.qH=function(){return null};z.y(sM,nM);sM.prototype.qH=function(a){var b;if("IMG"!==a.nodeName)return null;b=[];b.push('\x3cimg src\x3d"');b.push(z.Ma(a.src));b.push('"');a.getAttribute("eeimg")&&a.getAttribute("alt")&&b.push(' eeimg\x3d"'+z.Ma(a.getAttribute("eeimg"))+'" alt\x3d"'+z.Ma(a.getAttribute("alt"))+'"');b.push("\x3e");return b.join("")};z.y(tM,z.TE);z.y(uM,z.Lc);z.e=tM.prototype;z.e.show=function(){tM.v.show.call(this);this.sw.focus()};z.e.hide=function(){tM.v.hide.call(this)};
z.e.hy=function(){var a=z.um.Ln+"/upload_video",a=this.Cd.B("div","zm-img-uploader zm-img-uploader-upload-tab-selected",[this.Cd.B("div","zg-section",this.Cd.B("strong",null,"输入视频页地址：")),this.Cd.B("iframe",{id:"video_up_frame",src:"about:_blank",name:"video_up_frame",style:"visible:hidden;position:absolute;height:0;width:0;left:-9000px"}),this.ZG=this.Cd.B("form",{"class":"zg-section-title",target:"video_up_frame",method:"post",enctype:"multipart/form-data",action:a},[this.sw=this.Cd.B("input",{type:"text",
"class":"zg-form-text-input",name:"upload_file_url",autocomplete:"off"}),this.zo=this.Cd.B("a",{"class":"zg-btn-blue zm-uploader-button-fix",name:"save",href:"javascript:;"},"确定"),this.Cd.B("div","zm-video-uploader-info",[this.Nh=this.Cd.B("span",{style:"display:none","class":"zm-img-uploader-loading"},"正在上传"),this.Cf=this.Cd.B("span",{style:"display:none","class":"zm-img-uploader-error"},"插入视频失败，请稍后重试")])]),this.uT=this.Cd.B("div","zg-gray"),this.xo=this.Cd.B("div","zm-command",[this.Qx=this.Cd.B("a",
{href:"javascript:;"},"取消")])]);this.uT.innerHTML='我们目前支持\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://youku.com"\x3e优酷\x3c/a\x3e、\x3ca class\x3d"zg-link-gray" target\x3d"_blank" href\x3d"http://tudou.com"\x3e土豆\x3c/a\x3e、\x3ca href\x3d"http://video.sina.com.cn/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e新浪\x3c/a\x3e、\x3ca href\x3d"http://v.qq.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e腾讯\x3c/a\x3e、\x3ca href\x3d"http://www.56.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e56\x3c/a\x3e、\x3ca href\x3d"http://tv.sohu.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e搜狐\x3c/a\x3e、\x3ca href\x3d"http://www.iqiyi.com/" class\x3d"zg-link-gray" target\x3d"_blank"\x3e爱奇艺\x3c/a\x3e视频服务。\x3cbr /\x3e请不要上传与回答问题无关的视频，详细请看 \x3ca href\x3d"http://www.zhihu.com/question/20118966" target\x3d"_blank"\x3e知乎视频使用规范\x3c/a\x3e';
this.U.g(this.Qx,"click",function(){this.fp();this.hide()}).g(this.zo,"click",this.DK).g(this.xo,"click",this.Xa).g(this.ZG,"submit",function(){return vM(this,this.sw.value)}).g(z.X,"iframe_data",this.kx);this.LF=a;var b=new z.UE(this);b.La("插入视频").aa(a);a=z.XE(b);z.Lj(a,null);return a};z.e.DK=function(){if(this.sw.value){var a=z.Gr(this.sw.value);a&&vM(this,a)&&(z.P(this.Nh,!0),z.P(this.Cf,!1),this.ZG.submit())}};z.e.Xa=function(a){"save"===(a.target&&a.target.name)&&this.DK()};
z.e.kx=function(a){z.P(this.Nh,!1);this.nj(a.Wf)};z.e.nj=function(a){a&&!a.r?(this.dispatchEvent(this.Do(a.msg[0],a.msg[1],a.msg[2],a.msg[3],a.msg[4])),this.hide()):(a=a.msg,z.P(this.Nh,!1),this.Cf.innerHTML=a,z.P(this.Cf,!0))};z.e.Do=function(a,b,c,d,f){return new uM(a,b,c,d,f)};z.e.D=function(){this.U.dispose();this.U=null;tM.v.D.call(this)};z.y(wM,z.YE);z.e=wM.prototype;z.e.Fd=z.hb("VideoDialogPlugin");z.e.Df=function(a,b){var c=this.G;return c.Qf||(c.wg(),c.Qf)?wM.v.Df.call(this,a,b):!1};
z.e.ep=function(a){wM.v.ep.call(this,a)};z.e.gy=function(a){a=new tM(a);this.U.g(a,"ok",this.jp).g(a,"cancel",this.Dz);return a};z.e.D=function(){wM.v.D.call(this);this.U.dispose()};
z.e.jp=function(a){z.ZE(this);var b=z.zB(this),c=b.B("a",{"class":"video-link",href:a.IY,"data-src":a.QZ,"data-name":a.QM,"data-poster":a.poster,"data-videoid":a.PZ});z.of(c,a.QM);a=z.Qo(c);a=z.Ye(a+" ");var c=a.firstChild,d=z.aC(this.G);if(z.Av(d))d.fj(a),z.C?window.document.selection&&(b=window.document.selection.createRange(),b.move("character",-1),b.select()):(z.rv(c),b.eb().focus()),z.bC(this.G),this.G.Bf();else return null;this.U.removeAll()};z.e.Dz=function(){this.U.removeAll()};z.EB=!0;(function(a){z.yB.prototype.execCommand=function(b){var c=this.G;return z.eo(CM,b)&&!c.Qf?(c.wg(),!1):a.apply(this,arguments)}})(z.yB.prototype.execCommand);(function(a,b){z.YE.prototype.execCommand=function(c){var d=this.G;return!z.rb(b,c)||d.Qf||(d.wg(),d.Qf)?a.apply(this,arguments):!1}})(z.YE.prototype.execCommand,["+equation"]);xM="video";BM=z.Uc?"⌘":"ctrl";z.tI[xM]={Ba:xM,na:"插入视频",Wa:"tr-icon tr-video",factory:z.WF};
z.tI["+equation"]={Ba:"+equation",na:{}.F_,Wa:"tr-icon tr-equation",factory:z.WF};z.tI["+bold"].na="粗体 ("+BM+"+b)";z.tI["+italic"].na="斜体 ("+BM+"+i)";z.tI["+underline"].na="下划线 ("+BM+"+u)";z.tI["+superscript"].na="引用内容";z.tI["+insertOrderedList"].na="有序列表";z.tI["+insertUnorderedList"].na="无序列表";z.tI["+removeFormat"].na="清除格式";z.tI.image.na="插入图片";z.tI[xM].na="插入视频";z.tI["+equation"].na="插入公式";z.ka(yM);
yM.prototype.yf=function(a,b){this.config=b;var c,d,f;d=z.L("zm-editable-toolbar-container",a);c=z.L("zm-editable-editor-outer",a);f=z.L("zm-editable-editor-field-element",a);var g=new z.iC(f.id);g.kP=89;var h=zM(d,b);new DL(g,h);z.Ac(g,h);IJ(g,new fK);IJ(g,new sL);if(b.loremIpsum_&&(IJ(g,new uL(b.loremIpsum_)),z.B))g.on("load",function(){z.ld(g.m(),"focus",function(){g.execCommand("clearlorem",!0)})});IJ(g,new GK);IJ(g,new sM);IJ(g,new yL);d=new WL;IJ(g,d);IJ(g,new z.mG);IJ(g,new wM);IJ(g,new GL);
IJ(g,new qL);IJ(g,new YK);IJ(g,new LL);b.enableFullScreen&&(c=new z.fG({title:"写作模式",jl:c}),IJ(g,c));g.on("load",function(){b.useScraper_&&AM(g,h)},!1,this);return[g,h]};z.x("ZH.createRichTextEditor",function(a,b){return yM.ba().yf(a,b)});z.lg("richtexteditor");}).call(this, __z_z__);
//# sourceURL=/static/revved/-/js/closure/richtexteditor.72321947.js
